export interface CapitalManagementTranslations {
  badge: string
  h1prefix: string
  h1gradient: string
  intro1: string
  intro2: string
  tocTitle: string
  tocItems: string[]
  s1Title: string
  s1p1: string
  s1p2: string
  s1quote: string
  s2Title: string
  s2intro: string
  s2items: string[]
  s3Title: string
  s3intro: string
  s3card1Title: string
  s3card1Text: string
  s3card2Title: string
  s3card2Text: string
  s3card3Title: string
  s3card3Text: string
  s4Title: string
  s4intro: string
  tableHeaders: [string, string, string]
  tableRows: [string, string, string][]
  s4conclusion: string
  s5Title: string
  s5p1: string
  s5p2: string
  card1Title: string
  card1Desc: string
  card2Title: string
  card2Desc: string
  card3Title: string
  card3Desc: string
  s6Title: string
  step1Title: string
  step1p1: string
  step1p2: string
  step1note: string
  step2Title: string
  step2p1: string
  step2p2: string
  step3Title: string
  step3p1: string
  step3p2: string
  step3p3: string
  faqTitle: string
  faq1q: string
  faq1a: string
  faq2q: string
  faq2a: string
  faq3q: string
  faq3a: string
  faq4q: string
  faq4a: string
  ctaTitle: string
  ctaDesc: string
  ctaButton: string
  ctaNote: string
}

export const capitalManagementContent: Record<string, CapitalManagementTranslations> = {
  it: {
    badge: 'Guida · Gestione Portafoglio',
    h1prefix: 'Come Ribilanciare il Portafoglio di Investimenti: ',
    h1gradient: 'Guida Pratica e Tool Automatico',
    intro1: 'Il <strong>ribilanciamento del portafoglio</strong> è una delle operazioni più importanti per ogni investitore a lungo termine, eppure viene spesso trascurata. I mercati non si muovono tutti nella stessa direzione: azioni che crescono più rapidamente delle obbligazioni, un settore che sovraperforma gli altri, nuovi apporti di capitale — tutte situazioni che nel tempo modificano la composizione originale del portafoglio e alterano il profilo di rischio che avevi pianificato.',
    intro2: 'In questa guida scoprirai cos\'è il ribilanciamento, perché è essenziale, quando farlo e come semplificarlo con la funzione <strong>Capital Management</strong> integrata in DonkyCapital — senza fogli Excel, senza calcoli manuali.',
    tocTitle: 'Indice dei contenuti',
    tocItems: [
      'Cos\'è il ribilanciamento del portafoglio',
      'Perché il portafoglio si sbilancia nel tempo',
      'Quando ribilanciare: le strategie più efficaci',
      'Come ribilanciare senza costi fiscali eccessivi',
      'Il Capital Management di DonkyCapital',
      'Tutorial passo per passo',
      'Domande frequenti',
    ],
    s1Title: 'Cos\'è il ribilanciamento del portafoglio',
    s1p1: 'Il <strong>rebalancing</strong> (ribilanciamento) consiste nel riportare i pesi degli asset di un portafoglio alla composizione originale o target. Immagina di aver pianificato un\'allocazione 60% azionaria e 40% obbligazionaria. Dopo un anno di rialzi delle borse, il rapporto si è spostato a 72% azioni e 28% obbligazioni: stai correndo un rischio maggiore rispetto a quello che avevi pianificato.',
    s1p2: 'Ribilanciare significa correggere questa deriva: vendi una parte delle posizioni sovraesposte o acquisti quelle sottopesate, fino a tornare alla composizione pianificata. Lo stesso principio vale per un portafoglio di ETF, per un\'allocazione per settori, per valuta o per area geografica.',
    s1quote: 'Il ribilanciamento non è speculazione — è disciplina. È il meccanismo che ti permette di vendere alto e comprare basso in modo sistematico, senza affidarti all\'emotività del momento.',
    s2Title: 'Perché il portafoglio si sbilancia nel tempo',
    s2intro: 'La deriva del portafoglio è inevitabile e dipende da più fattori:',
    s2items: [
      '<strong>Crescita differenziata degli asset:</strong> azioni e obbligazioni non crescono allo stesso ritmo. In fasi di bull market azionario, le azioni tendono a sovraperformare alterando il peso relativo.',
      '<strong>Dividendi e cedole non reinvestiti:</strong> se la liquidità generata non viene redistribuita in modo proporzionale, si accumulano squilibri progressivi.',
      '<strong>Nuovi apporti di capitale:</strong> ogni versamento mensile o una tantum, se non distribuito correttamente, altera i pesi del portafoglio.',
      '<strong>Prelievi parziali:</strong> le riduzioni di capitale che non rispettano la composizione target modificano le proporzioni residue.',
      '<strong>Effetto cambio:</strong> se hai ETF denominati in USD o GBP, le fluttuazioni del cambio EUR/valuta modificano il peso reale nella tua valuta di riferimento.',
    ],
    s3Title: 'Quando ribilanciare: le strategie più efficaci',
    s3intro: 'Non esiste una risposta universale alla domanda <em>"ogni quanto devo ribilanciare il portafoglio?"</em>. Dipende dalla tua strategia, dai costi di transazione e dall\'impatto fiscale. Esistono però tre approcci principali:',
    s3card1Title: 'Ribilanciamento a calendario',
    s3card1Text: 'Scegli una frequenza fissa — trimestrale, semestrale o annuale — e verifichi la composizione del portafoglio a prescindere dai movimenti di mercato. È semplice da pianificare e aiuta a mantenere la disciplina evitando decisioni emotive. Lo svantaggio è che potresti intervenire quando il drift è ancora minimo, sostenendo costi di transazione non necessari.',
    s3card2Title: 'Ribilanciamento a soglia (threshold rebalancing)',
    s3card2Text: 'Agisci solo quando un asset si discosta di più del 5% (o 10%) dalla sua allocazione target. Ad esempio, se un ETF azionario pesa il 40% nel piano ma ha raggiunto il 47%, è il momento di intervenire. Questo approccio riduce i costi di transazione nei periodi stabili, ma richiede un monitoraggio più frequente.',
    s3card3Title: 'Approccio misto (consigliato)',
    s3card3Text: 'La strategia più efficiente per la maggior parte degli investitori: <strong>controllo trimestrale</strong>, ma azione solo se il drift supera il 5%. Così eviti transazioni inutili nei periodi stabili, mantieni comunque una disciplina temporale e non rischi di accorgerti troppo tardi di uno squilibrio significativo.',
    s4Title: 'Come ribilanciare senza costi fiscali eccessivi',
    s4intro: 'Il ribilanciamento classico prevede di vendere i vincitori e comprare i perdenti. Ogni vendita in guadagno, però, genera tassazione sulle plusvalenze. Esistono strategie alternative per minimizzare l\'impatto fiscale:',
    tableHeaders: ['Strategia', 'Vantaggio', 'Limite'],
    tableRows: [
      ['Buy-only rebalancing', 'Nessuna plusvalenza realizzata, fiscalmente ottimale', 'Richiede nuova liquidità, funziona solo se il drift non è troppo ampio'],
      ['Full rebalancing (buy & sell)', 'Riporta esattamente alla composizione target', 'Genera plusvalenze tassabili sulle posizioni vendute in guadagno'],
      ['Withdrawal rebalancing', 'Ideale in fase di decumulazione', 'Applicabile solo se stai prelevando capitale dal portafoglio'],
    ],
    s4conclusion: 'In tutti e tre i casi, la funzione <strong>Capital Management</strong> di DonkyCapital supporta nativamente ogni strategia: puoi scegliere se aggiungere capitale, ridurlo o ribilanciare sulla composizione target.',
    s5Title: 'Il Capital Management di DonkyCapital',
    s5p1: 'DonkyCapital integra direttamente nel tracker di portafoglio una funzione di <strong>Capital Management</strong> che calcola automaticamente gli ordini necessari per ribilanciare o redistribuire il capitale — in pochi secondi, con i prezzi di mercato aggiornati, senza formule e senza Excel.',
    s5p2: 'La funzione è disponibile per tutti i portafogli caricati sulla piattaforma, indipendentemente dal broker (Fineco, DeGiro, Scalable Capital, Directa e altri).',
    card1Title: 'Increase Capital',
    card1Desc: 'Calcola gli ordini di acquisto per aggiungere nuova liquidità mantenendo le allocazioni attuali.',
    card2Title: 'Reduce Capital',
    card2Desc: 'Calcola gli ordini di vendita per prelevare capitale mantenendo le proporzioni invariate.',
    card3Title: 'Rebalance',
    card3Desc: 'Calcola acquisti e vendite per riportare il portafoglio alla composizione di un portafoglio di riferimento.',
    s6Title: 'Tutorial passo per passo',
    step1Title: '01. Increase Capital — aggiungere liquidità senza sbilanciare',
    step1p1: 'Hai nuova liquidità da investire e vuoi distribuirla proporzionalmente sulle posizioni esistenti? Seleziona <strong>Increase Capital</strong>, inserisci l\'importo disponibile (es. 10.000€) e premi <strong>Calcola</strong>.',
    step1p2: 'Il sistema elabora i prezzi attuali di mercato e restituisce il piano di acquisto ottimale: per ogni strumento in portafoglio vedrai la quantità attuale, la quantità target, il delta (pezzi da acquistare) e il valore dell\'ordine. La liquidità residua dopo gli acquisti è visibile in tempo reale.',
    step1note: 'Puoi scaricare i risultati in formato CSV per eseguire gli ordini direttamente sulla piattaforma del tuo broker.',
    step2Title: '02. Reduce Capital — prelevare senza sbilanciare',
    step2p1: 'Hai bisogno di liquidare una parte del portafoglio? Con <strong>Reduce Capital</strong> inserisci l\'importo da prelevare e il sistema calcola quali titoli vendere e in quale quantità, mantenendo invariate le proporzioni del portafoglio residuo.',
    step2p2: 'Il risultato mostra gli ordini di vendita (SELL) con quantità esatte e valore per ogni strumento, più la liquidità disponibile dopo le vendite. Utile soprattutto nella fase di decumulazione o quando devi far fronte a spese impreviste.',
    step3Title: '03. Rebalance — tornare alla composizione target',
    step3p1: 'È la modalità più potente. Seleziona il <strong>portafoglio di riferimento</strong> — che può essere lo stesso portafoglio a una data precedente, oppure un <strong>portafoglio completamente diverso</strong> come modello target — e la <strong>data di riferimento</strong>: DonkyCapital calcolerà esattamente quanti titoli comprare, vendere o mantenere (HOLD) per riportare il portafoglio corrente alla composizione desiderata.',
    step3p2: 'Questo è particolarmente utile se gestisci più portafogli: puoi allineare un portafoglio satellite alla composizione di un portafoglio principale, o replicare la struttura di un portafoglio modello su un nuovo conto broker.',
    step3p3: 'Se il portafoglio è già allineato alla composizione target, il risultato mostrerà tutti gli strumenti con azione <strong>HOLD</strong> e importi di acquisto/vendita a zero. Puoi anche modificare manualmente le <strong>percentuali target</strong> direttamente nella tabella dei risultati e premere <strong>Ricalcola</strong> per aggiornare il piano in tempo reale — senza dover ricominciare da capo. Questo ti dà la massima flessibilità per testare scenari diversi e ottimizzare la distribuzione prima di eseguire qualsiasi ordine.',
    faqTitle: 'Domande frequenti sul ribilanciamento',
    faq1q: 'Con quale frequenza devo ribilanciare il portafoglio?',
    faq1a: 'Per la maggior parte degli investitori una verifica trimestrale è sufficiente. L\'importante è definire una soglia di drift (es. ±5%) oltre la quale intervenire. Ribilanciare troppo spesso aumenta i costi di transazione e può generare plusvalenze tassabili senza reale necessità.',
    faq2q: 'È meglio ribilanciare solo comprando o anche vendendo?',
    faq2a: 'Dipende dalla tua fase di investimento. Se sei in accumulo e hai nuova liquidità disponibile, il buy-only rebalancing è spesso preferibile perché evita la tassazione sulle plusvalenze. Se il drift è molto ampio o sei in decumulazione, il rebalancing completo con acquisti e vendite è più appropriato.',
    faq3q: 'Il ribilanciamento del portafoglio genera tassazione?',
    faq3a: 'Sì: ogni vendita di strumenti finanziari in guadagno è soggetta a tassazione sulle plusvalenze. Per questo il buy-only rebalancing è spesso consigliato durante la fase di accumulo. La funzione "Rebalance" di DonkyCapital mostra chiaramente gli ordini di vendita (SELL) in modo da poter valutare l\'impatto fiscale prima di eseguire.',
    faq4q: 'Il Capital Management funziona con tutti i broker?',
    faq4a: 'Sì. Il Capital Management di DonkyCapital funziona con tutti i portafogli caricati sulla piattaforma, indipendentemente dal broker: Fineco, DeGiro, Scalable Capital, Directa e altri. Il sistema recupera i dati aggiornati e calcola gli ordini in base ai prezzi correnti di mercato.',
    ctaTitle: 'Inizia a gestire il tuo portafoglio in modo intelligente',
    ctaDesc: 'Con DonkyCapital hai il Capital Management, widget analitici avanzati e il tracciamento unificato di tutti i tuoi broker — tutto in un\'unica dashboard. Richiedi l\'accesso anticipato gratuitamente.',
    ctaButton: 'Prova DonkyCapital gratis',
    ctaNote: 'Early access gratuito · Nessuna carta di credito richiesta',
  },

  en: {
    badge: 'Guide · Portfolio Management',
    h1prefix: 'How to Rebalance Your Investment Portfolio: ',
    h1gradient: 'Practical Guide & Automatic Tool',
    intro1: '<strong>Portfolio rebalancing</strong> is one of the most important operations for any long-term investor, yet it is often overlooked. Markets do not all move in the same direction: stocks growing faster than bonds, a sector outperforming others, new capital contributions — all situations that over time alter the original portfolio composition and change the risk profile you had planned.',
    intro2: 'In this complete guide you will learn what rebalancing is, why it is essential, when to do it, and how to simplify it with the <strong>Capital Management</strong> feature built into DonkyCapital — no Excel spreadsheets, no manual calculations.',
    tocTitle: 'Table of Contents',
    tocItems: [
      'What is portfolio rebalancing',
      'Why portfolios drift over time',
      'When to rebalance: the most effective strategies',
      'How to rebalance without excessive tax costs',
      'DonkyCapital\'s Capital Management',
      'Step-by-step tutorial',
      'Frequently asked questions',
    ],
    s1Title: 'What is portfolio rebalancing',
    s1p1: '<strong>Rebalancing</strong> consists of bringing the weights of a portfolio\'s assets back to their original or target composition. Imagine you planned a 60% equity and 40% bond allocation. After a year of stock market gains, the ratio has shifted to 72% stocks and 28% bonds: you are now taking on more risk than you had planned.',
    s1p2: 'Rebalancing means correcting this drift: you sell part of the overexposed positions or buy the underweighted ones, until you return to the planned composition. The same principle applies to an ETF portfolio, a sector allocation, or a currency and geographic breakdown.',
    s1quote: 'Rebalancing is not speculation — it is discipline. It is the mechanism that allows you to sell high and buy low in a systematic way, without relying on the emotion of the moment.',
    s2Title: 'Why portfolios drift over time',
    s2intro: 'Portfolio drift is inevitable and depends on several factors:',
    s2items: [
      '<strong>Differentiated asset growth:</strong> stocks and bonds do not grow at the same rate. In equity bull markets, stocks tend to outperform, altering their relative weight.',
      '<strong>Uninvested dividends and coupons:</strong> if the generated cash is not redistributed proportionally, progressive imbalances accumulate.',
      '<strong>New capital contributions:</strong> each monthly or lump-sum deposit, if not distributed correctly, alters the portfolio weights.',
      '<strong>Partial withdrawals:</strong> capital reductions that do not respect the target composition modify the remaining proportions.',
      '<strong>Currency effect:</strong> if you hold ETFs denominated in USD or GBP, EUR/currency fluctuations modify the real weight in your reference currency.',
    ],
    s3Title: 'When to rebalance: the most effective strategies',
    s3intro: 'There is no universal answer to <em>"how often should I rebalance my portfolio?"</em>. It depends on your strategy, transaction costs, and tax impact. There are, however, three main approaches:',
    s3card1Title: 'Calendar-based rebalancing',
    s3card1Text: 'Choose a fixed frequency — quarterly, semi-annual, or annual — and check the portfolio composition regardless of market movements. It is simple to plan and helps maintain discipline by avoiding emotional decisions. The downside is that you might act when the drift is still minimal, incurring unnecessary transaction costs.',
    s3card2Title: 'Threshold rebalancing',
    s3card2Text: 'Act only when an asset deviates more than 5% (or 10%) from its target allocation. For example, if an equity ETF weighs 40% in the plan but has reached 47%, it is time to act. This approach reduces transaction costs during stable periods, but requires more frequent monitoring.',
    s3card3Title: 'Mixed approach (recommended)',
    s3card3Text: 'The most efficient strategy for most investors: <strong>quarterly review</strong>, but action only if the drift exceeds 5%. This avoids unnecessary transactions during stable periods, maintains time discipline, and ensures you do not notice a significant imbalance too late.',
    s4Title: 'How to rebalance without excessive tax costs',
    s4intro: 'Classic rebalancing involves selling winners and buying losers. However, any sale at a gain generates taxation on capital gains. There are alternative strategies to minimize the tax impact:',
    tableHeaders: ['Strategy', 'Advantage', 'Limitation'],
    tableRows: [
      ['Buy-only rebalancing', 'No realized capital gains, fiscally optimal', 'Requires new liquidity, works only if drift is not too wide'],
      ['Full rebalancing (buy & sell)', 'Brings back exactly to target composition', 'Generates taxable capital gains on positions sold at a profit'],
      ['Withdrawal rebalancing', 'Ideal during the decumulation phase', 'Only applicable if you are withdrawing capital from the portfolio'],
    ],
    s4conclusion: 'In all three cases, DonkyCapital\'s <strong>Capital Management</strong> function natively supports each strategy: you can choose to add capital, reduce it, or rebalance against a target composition.',
    s5Title: 'DonkyCapital\'s Capital Management',
    s5p1: 'DonkyCapital integrates directly into the portfolio tracker a <strong>Capital Management</strong> function that automatically calculates the orders needed to rebalance or redistribute capital — in seconds, with up-to-date market prices, without formulas and without Excel.',
    s5p2: 'The function is available for all portfolios loaded on the platform, regardless of the broker (Fineco, DeGiro, Scalable Capital, Directa and others).',
    card1Title: 'Increase Capital',
    card1Desc: 'Calculates buy orders to add new liquidity while maintaining current allocations.',
    card2Title: 'Reduce Capital',
    card2Desc: 'Calculates sell orders to withdraw capital while keeping proportions unchanged.',
    card3Title: 'Rebalance',
    card3Desc: 'Calculates buys and sells to bring the portfolio to the composition of a reference portfolio.',
    s6Title: 'Step-by-step tutorial',
    step1Title: '01. Increase Capital — add liquidity without unbalancing',
    step1p1: 'Do you have new liquidity to invest and want to distribute it proportionally across existing positions? Select <strong>Increase Capital</strong>, enter the available amount (e.g. €10,000) and press <strong>Calculate</strong>.',
    step1p2: 'The system processes current market prices and returns the optimal purchase plan: for each instrument in the portfolio you will see the current quantity, target quantity, delta (shares to buy) and the order value. Remaining liquidity after purchases is visible in real time.',
    step1note: 'You can download the results in CSV format to place orders directly on your broker\'s platform.',
    step2Title: '02. Reduce Capital — withdraw without unbalancing',
    step2p1: 'Do you need to liquidate part of your portfolio? With <strong>Reduce Capital</strong> enter the amount to withdraw and the system calculates which securities to sell and in what quantity, keeping the proportions of the remaining portfolio unchanged.',
    step2p2: 'The result shows sell orders (SELL) with exact quantities and values for each instrument, plus available liquidity after the sales. Especially useful during the decumulation phase or when you need to cover unexpected expenses.',
    step3Title: '03. Rebalance — return to target composition',
    step3p1: 'This is the most powerful mode. Select the <strong>reference portfolio</strong> — which can be the same portfolio at a previous date, or a <strong>completely different portfolio</strong> as a model target — and the <strong>reference date</strong>: DonkyCapital will calculate exactly how many securities to buy, sell, or hold (HOLD) to bring the current portfolio to the desired composition.',
    step3p2: 'This is particularly useful if you manage multiple portfolios: you can align a satellite portfolio to the composition of a main portfolio, or replicate the structure of a model portfolio on a new broker account.',
    step3p3: 'If the portfolio is already aligned to the target composition, the result will show all instruments with action <strong>HOLD</strong> and zero buy/sell amounts. You can also manually modify the <strong>target percentages</strong> directly in the results table and press <strong>Recalculate</strong> to update the plan in real time — without having to start over. This gives you maximum flexibility to test different scenarios and optimize the distribution before executing any order.',
    faqTitle: 'Frequently asked questions about rebalancing',
    faq1q: 'How often should I rebalance my portfolio?',
    faq1a: 'For most investors, a quarterly review is sufficient. The important thing is to define a drift threshold (e.g. ±5%) beyond which to act. Rebalancing too often increases transaction costs and can generate taxable capital gains unnecessarily.',
    faq2q: 'Is it better to rebalance only by buying or also by selling?',
    faq2a: 'It depends on your investment phase. If you are in accumulation and have new liquidity available, buy-only rebalancing is often preferable because it avoids taxation on capital gains. If the drift is very wide or you are in decumulation, full rebalancing with both buys and sells is more appropriate.',
    faq3q: 'Does portfolio rebalancing generate taxation?',
    faq3a: 'Yes: any sale of financial instruments at a profit is subject to capital gains tax. This is why buy-only rebalancing is often recommended during the accumulation phase. DonkyCapital\'s "Rebalance" function clearly shows sell orders (SELL) so you can evaluate the tax impact before executing.',
    faq4q: 'Does Capital Management work with all brokers?',
    faq4a: 'Yes. DonkyCapital\'s Capital Management works with all portfolios loaded on the platform, regardless of the broker: Fineco, DeGiro, Scalable Capital, Directa and others. The system retrieves up-to-date data and calculates orders based on current market prices.',
    ctaTitle: 'Start managing your portfolio intelligently',
    ctaDesc: 'With DonkyCapital you get Capital Management, advanced analytics widgets and unified tracking of all your brokers — all in one dashboard. Request early access for free.',
    ctaButton: 'Try DonkyCapital for free',
    ctaNote: 'Free early access · No credit card required',
  },

  de: {
    badge: 'Leitfaden · Portfolioverwaltung',
    h1prefix: 'Portfolio Rebalancing: ',
    h1gradient: 'Praxisleitfaden & Automatisches Tool',
    intro1: 'Das <strong>Rebalancing des Portfolios</strong> ist eine der wichtigsten Maßnahmen für jeden langfristigen Investor, wird aber häufig vernachlässigt. Die Märkte bewegen sich nicht alle in dieselbe Richtung: Aktien, die schneller als Anleihen wachsen, ein Sektor, der andere übertrifft, neue Kapitalzuflüsse — all das verändert im Laufe der Zeit die ursprüngliche Portfoliozusammensetzung und das geplante Risikoprofil.',
    intro2: 'In diesem vollständigen Leitfaden erfährst du, was Rebalancing ist, warum es wichtig ist, wann du es durchführen solltest und wie du es mit der <strong>Capital Management</strong>-Funktion von DonkyCapital vereinfachst — ohne Excel-Tabellen, ohne manuelle Berechnungen.',
    tocTitle: 'Inhaltsverzeichnis',
    tocItems: [
      'Was ist Portfolio-Rebalancing?',
      'Warum verschiebt sich das Portfolio im Laufe der Zeit?',
      'Wann rebalancieren: die effektivsten Strategien',
      'Steueroptimiertes Rebalancing',
      'Das Capital Management von DonkyCapital',
      'Schritt-für-Schritt-Tutorial',
      'Häufig gestellte Fragen',
    ],
    s1Title: 'Was ist Portfolio-Rebalancing?',
    s1p1: '<strong>Rebalancing</strong> bedeutet, die Gewichtungen der Assets eines Portfolios auf ihre ursprüngliche oder Zielzusammensetzung zurückzuführen. Stell dir vor, du hast eine Allokation von 60% Aktien und 40% Anleihen geplant. Nach einem Jahr Börsenhausse hat sich das Verhältnis auf 72% Aktien und 28% Anleihen verschoben: Du trägst jetzt mehr Risiko als geplant.',
    s1p2: 'Rebalancing bedeutet, diese Drift zu korrigieren: Du verkaufst einen Teil der übergewichteten Positionen oder kaufst die untergewichteten, bis du zur geplanten Zusammensetzung zurückkehrst. Das gleiche Prinzip gilt für ein ETF-Depot, eine Sektorallokation oder eine Währungs- und Regionsaufteilung.',
    s1quote: 'Rebalancing ist keine Spekulation — es ist Disziplin. Es ist der Mechanismus, der es dir erlaubt, systematisch hoch zu verkaufen und niedrig zu kaufen, ohne dich auf die Emotionen des Moments zu verlassen.',
    s2Title: 'Warum verschiebt sich das Portfolio im Laufe der Zeit?',
    s2intro: 'Die Portfoliodrift ist unvermeidlich und hängt von mehreren Faktoren ab:',
    s2items: [
      '<strong>Unterschiedliches Asset-Wachstum:</strong> Aktien und Anleihen wachsen nicht im gleichen Tempo. In Aktien-Bullenmärkten tendieren Aktien zur Outperformance, was ihr relatives Gewicht verändert.',
      '<strong>Nicht reinvestierte Dividenden und Kupons:</strong> Wenn die generierten Erträge nicht proportional reinvestiert werden, entstehen progressive Ungleichgewichte.',
      '<strong>Neue Kapitalzuflüsse:</strong> Jede monatliche oder einmalige Einzahlung, die nicht korrekt verteilt wird, verändert die Portfoliogewichtungen.',
      '<strong>Teilentnahmen:</strong> Kapitalentnahmen, die die Zielgewichtung nicht berücksichtigen, verändern die verbleibenden Proportionen.',
      '<strong>Währungseffekt:</strong> Bei ETFs in USD oder GBP verändert die EUR/Währungsfluktuation das reale Gewicht in deiner Referenzwährung.',
    ],
    s3Title: 'Wann rebalancieren: die effektivsten Strategien',
    s3intro: 'Es gibt keine universelle Antwort auf die Frage: <em>„Wie oft sollte ich mein Portfolio rebalancieren?"</em>. Es hängt von deiner Strategie, den Transaktionskosten und den steuerlichen Auswirkungen ab. Es gibt jedoch drei Hauptansätze:',
    s3card1Title: 'Kalenderbasiertes Rebalancing',
    s3card1Text: 'Wähle eine feste Häufigkeit — vierteljährlich, halbjährlich oder jährlich — und prüfe die Portfoliozusammensetzung unabhängig von Marktbewegungen. Einfach zu planen und hilft, Disziplin zu wahren. Der Nachteil: Du könntest eingreifen, wenn die Drift noch minimal ist, und unnötige Transaktionskosten verursachen.',
    s3card2Title: 'Schwellenwert-Rebalancing',
    s3card2Text: 'Handle nur, wenn ein Asset mehr als 5% (oder 10%) von seiner Zielallokation abweicht. Zum Beispiel: Wenn ein Aktien-ETF zu 40% geplant war, aber 47% erreicht hat, ist es Zeit zu handeln. Dieser Ansatz reduziert Transaktionskosten in stabilen Phasen, erfordert aber häufigere Überwachung.',
    s3card3Title: 'Gemischter Ansatz (empfohlen)',
    s3card3Text: 'Die effizienteste Strategie für die meisten Investoren: <strong>vierteljährliche Überprüfung</strong>, aber Aktion nur, wenn die Drift 5% überschreitet. So vermeidest du unnötige Transaktionen in stabilen Phasen, behältst eine zeitliche Disziplin und erkennst signifikante Ungleichgewichte rechtzeitig.',
    s4Title: 'Steueroptimiertes Rebalancing',
    s4intro: 'Klassisches Rebalancing bedeutet, Gewinner zu verkaufen und Verlierer zu kaufen. Jeder Verkauf mit Gewinn löst jedoch eine Kapitalertragsteuer aus. Es gibt alternative Strategien zur Minimierung der steuerlichen Auswirkungen:',
    tableHeaders: ['Strategie', 'Vorteil', 'Einschränkung'],
    tableRows: [
      ['Buy-only Rebalancing', 'Keine realisierten Kursgewinne, steueroptimal', 'Erfordert neue Liquidität, funktioniert nur bei kleiner Drift'],
      ['Volles Rebalancing (Kauf & Verkauf)', 'Bringt exakt zur Zielgewichtung zurück', 'Erzeugt steuerpflichtige Kursgewinne auf verkaufte Positionen'],
      ['Entnahme-Rebalancing', 'Ideal in der Entnahmephase', 'Nur anwendbar bei Kapitalentnahme aus dem Portfolio'],
    ],
    s4conclusion: 'In allen drei Fällen unterstützt DonkyCapitals <strong>Capital Management</strong> jede Strategie nativ: Du kannst wählen, ob du Kapital hinzufügen, reduzieren oder auf eine Zielgewichtung rebalancieren möchtest.',
    s5Title: 'Das Capital Management von DonkyCapital',
    s5p1: 'DonkyCapital integriert direkt im Portfolio-Tracker eine <strong>Capital Management</strong>-Funktion, die automatisch die notwendigen Orders berechnet, um das Portfolio zu rebalancieren oder Kapital umzuschichten — in Sekunden, mit aktuellen Marktpreisen, ohne Formeln und ohne Excel.',
    s5p2: 'Die Funktion ist für alle auf der Plattform geladenen Portfolios verfügbar, unabhängig vom Broker (Fineco, DeGiro, Scalable Capital, Directa und andere).',
    card1Title: 'Increase Capital',
    card1Desc: 'Berechnet Kauforders, um neue Liquidität hinzuzufügen und dabei die aktuelle Allokation beizubehalten.',
    card2Title: 'Reduce Capital',
    card2Desc: 'Berechnet Verkaufsorders, um Kapital zu entnehmen und dabei die Proportionen unverändert zu lassen.',
    card3Title: 'Rebalance',
    card3Desc: 'Berechnet Käufe und Verkäufe, um das Portfolio auf die Zusammensetzung eines Referenzportfolios zurückzuführen.',
    s6Title: 'Schritt-für-Schritt-Tutorial',
    step1Title: '01. Increase Capital — Liquidität hinzufügen ohne Ungleichgewicht',
    step1p1: 'Du hast neue Liquidität zu investieren und möchtest sie proportional auf bestehende Positionen verteilen? Wähle <strong>Increase Capital</strong>, gib den verfügbaren Betrag ein (z.B. 10.000€) und drücke <strong>Berechnen</strong>.',
    step1p2: 'Das System verarbeitet aktuelle Marktpreise und liefert den optimalen Kaufplan: Für jedes Instrument siehst du die aktuelle Menge, die Zielmenge, das Delta (zu kaufende Stücke) und den Auftragswert. Die verbleibende Liquidität nach den Käufen ist in Echtzeit sichtbar.',
    step1note: 'Du kannst die Ergebnisse als CSV herunterladen, um Orders direkt auf der Plattform deines Brokers aufzugeben.',
    step2Title: '02. Reduce Capital — Kapital entnehmen ohne Ungleichgewicht',
    step2p1: 'Musst du einen Teil des Portfolios liquidieren? Mit <strong>Reduce Capital</strong> gibst du den zu entnehmenden Betrag ein, und das System berechnet, welche Wertpapiere in welcher Menge zu verkaufen sind, um die Proportionen des verbleibenden Portfolios beizubehalten.',
    step2p2: 'Das Ergebnis zeigt Verkaufsorders (SELL) mit genauen Mengen und Werten für jedes Instrument sowie die verfügbare Liquidität nach den Verkäufen. Besonders nützlich in der Entnahmephase oder bei unerwarteten Ausgaben.',
    step3Title: '03. Rebalance — zur Zielgewichtung zurückkehren',
    step3p1: 'Dies ist der leistungsstärkste Modus. Wähle das <strong>Referenzportfolio</strong> — das kann dasselbe Portfolio zu einem früheren Datum sein oder ein <strong>völlig anderes Portfolio</strong> als Zielmodell — und das <strong>Referenzdatum</strong>: DonkyCapital berechnet genau, wie viele Wertpapiere gekauft, verkauft oder gehalten werden sollen (HOLD).',
    step3p2: 'Das ist besonders nützlich, wenn du mehrere Portfolios verwaltest: Du kannst ein Satellitenportfolio auf die Zusammensetzung eines Hauptportfolios ausrichten oder die Struktur eines Modellportfolios auf einem neuen Broker-Konto replizieren.',
    step3p3: 'Wenn das Portfolio bereits mit der Zielzusammensetzung übereinstimmt, zeigt das Ergebnis alle Instrumente mit Aktion <strong>HOLD</strong>. Du kannst die <strong>Zielprozentsätze</strong> direkt in der Ergebnistabelle anpassen und <strong>Neu berechnen</strong> drücken, um den Plan in Echtzeit zu aktualisieren — ohne von vorne anfangen zu müssen. So hast du maximale Flexibilität, verschiedene Szenarien zu testen.',
    faqTitle: 'Häufig gestellte Fragen zum Rebalancing',
    faq1q: 'Wie oft sollte ich mein Portfolio rebalancieren?',
    faq1a: 'Für die meisten Investoren reicht eine vierteljährliche Überprüfung aus. Wichtig ist, einen Drift-Schwellenwert (z.B. ±5%) festzulegen, ab dem eingegriffen wird. Zu häufiges Rebalancing erhöht Transaktionskosten und kann unnötigerweise steuerpflichtige Gewinne auslösen.',
    faq2q: 'Ist es besser, nur durch Käufe oder auch durch Verkäufe zu rebalancieren?',
    faq2a: 'Das hängt von deiner Investitionsphase ab. In der Ansparphase mit verfügbarer neuer Liquidität ist Buy-only Rebalancing oft vorzuziehen, da es Kapitalertragsteuer vermeidet. Bei sehr großer Drift oder in der Entnahmephase ist vollständiges Rebalancing mit Käufen und Verkäufen angemessener.',
    faq3q: 'Löst Portfolio-Rebalancing Steuern aus?',
    faq3a: 'Ja: Jeder Verkauf von Finanzinstrumenten mit Gewinn unterliegt der Kapitalertragsteuer. Deshalb wird Buy-only Rebalancing in der Ansparphase oft empfohlen. Die "Rebalance"-Funktion von DonkyCapital zeigt Verkaufsorders (SELL) klar an, damit du die steuerlichen Auswirkungen vor der Ausführung bewerten kannst.',
    faq4q: 'Funktioniert Capital Management mit allen Brokern?',
    faq4a: 'Ja. DonkyCapitals Capital Management funktioniert mit allen auf der Plattform geladenen Portfolios, unabhängig vom Broker: Fineco, DeGiro, Scalable Capital, Directa und andere. Das System ruft aktuelle Daten ab und berechnet Orders auf Basis aktueller Marktpreise.',
    ctaTitle: 'Starte mit intelligentem Portfolio-Management',
    ctaDesc: 'Mit DonkyCapital hast du Capital Management, erweiterte Analyse-Widgets und die zentrale Verwaltung aller deiner Broker — alles in einem Dashboard. Beantrage kostenlosen Early Access.',
    ctaButton: 'DonkyCapital kostenlos testen',
    ctaNote: 'Kostenloser Early Access · Keine Kreditkarte erforderlich',
  },

  fr: {
    badge: 'Guide · Gestion de Portefeuille',
    h1prefix: 'Comment Rééquilibrer son Portefeuille : ',
    h1gradient: 'Guide Pratique & Outil Automatique',
    intro1: 'Le <strong>rééquilibrage de portefeuille</strong> est l\'une des opérations les plus importantes pour tout investisseur à long terme, pourtant souvent négligée. Les marchés ne progressent pas tous dans la même direction : des actions qui croissent plus vite que les obligations, un secteur qui surperforme les autres, de nouveaux apports de capital — autant de situations qui, au fil du temps, modifient la composition initiale du portefeuille et altèrent le profil de risque planifié.',
    intro2: 'Dans ce guide complet, vous découvrirez ce qu\'est le rééquilibrage, pourquoi il est essentiel, quand le réaliser et comment le simplifier grâce à la fonctionnalité <strong>Capital Management</strong> intégrée à DonkyCapital — sans tableurs Excel, sans calculs manuels.',
    tocTitle: 'Sommaire',
    tocItems: [
      'Qu\'est-ce que le rééquilibrage de portefeuille ?',
      'Pourquoi le portefeuille se déséquilibre-t-il ?',
      'Quand rééquilibrer : les stratégies les plus efficaces',
      'Comment rééquilibrer sans coûts fiscaux excessifs',
      'Le Capital Management de DonkyCapital',
      'Tutoriel pas à pas',
      'Questions fréquentes',
    ],
    s1Title: 'Qu\'est-ce que le rééquilibrage de portefeuille ?',
    s1p1: 'Le <strong>rebalancing</strong> (rééquilibrage) consiste à ramener les pondérations des actifs d\'un portefeuille à leur composition initiale ou cible. Imaginez que vous ayez planifié une allocation de 60 % en actions et 40 % en obligations. Après une année de hausse boursière, le ratio est passé à 72 % actions et 28 % obligations : vous prenez désormais plus de risque que prévu.',
    s1p2: 'Rééquilibrer signifie corriger cette dérive : vous vendez une partie des positions surpondérées ou achetez les sous-pondérées, jusqu\'à retrouver la composition planifiée. Le même principe s\'applique à un portefeuille d\'ETF, à une allocation sectorielle ou à une répartition par devise et zone géographique.',
    s1quote: 'Le rééquilibrage n\'est pas de la spéculation — c\'est de la discipline. C\'est le mécanisme qui vous permet de vendre haut et d\'acheter bas de manière systématique, sans vous fier à l\'émotion du moment.',
    s2Title: 'Pourquoi le portefeuille se déséquilibre-t-il ?',
    s2intro: 'La dérive du portefeuille est inévitable et dépend de plusieurs facteurs :',
    s2items: [
      '<strong>Croissance différenciée des actifs :</strong> les actions et les obligations ne progressent pas au même rythme. En phase de marché haussier, les actions tendent à surperformer, modifiant leur poids relatif.',
      '<strong>Dividendes et coupons non réinvestis :</strong> si les revenus générés ne sont pas redistribués proportionnellement, des déséquilibres progressifs s\'accumulent.',
      '<strong>Nouveaux apports de capital :</strong> chaque versement mensuel ou ponctuel, s\'il n\'est pas correctement réparti, modifie les pondérations du portefeuille.',
      '<strong>Retraits partiels :</strong> les réductions de capital qui ne respectent pas la composition cible modifient les proportions restantes.',
      '<strong>Effet de change :</strong> si vous détenez des ETF libellés en USD ou GBP, les fluctuations EUR/devises modifient le poids réel dans votre devise de référence.',
    ],
    s3Title: 'Quand rééquilibrer : les stratégies les plus efficaces',
    s3intro: 'Il n\'existe pas de réponse universelle à la question <em>« à quelle fréquence dois-je rééquilibrer mon portefeuille ? »</em>. Cela dépend de votre stratégie, des frais de transaction et des implications fiscales. Il existe toutefois trois approches principales :',
    s3card1Title: 'Rééquilibrage calendaire',
    s3card1Text: 'Choisissez une fréquence fixe — trimestrielle, semestrielle ou annuelle — et vérifiez la composition du portefeuille indépendamment des mouvements du marché. Simple à planifier, il aide à maintenir la discipline. L\'inconvénient : vous pourriez intervenir quand la dérive est encore minime, entraînant des frais de transaction inutiles.',
    s3card2Title: 'Rééquilibrage par seuil',
    s3card2Text: 'Agissez uniquement lorsqu\'un actif s\'écarte de plus de 5 % (ou 10 %) de son allocation cible. Par exemple, si un ETF actions représente 40 % dans le plan mais atteint 47 %, il est temps d\'intervenir. Cette approche réduit les frais en période stable, mais nécessite une surveillance plus fréquente.',
    s3card3Title: 'Approche mixte (recommandée)',
    s3card3Text: 'La stratégie la plus efficace pour la plupart des investisseurs : <strong>révision trimestrielle</strong>, mais intervention uniquement si la dérive dépasse 5 %. Vous évitez les transactions inutiles en période stable tout en maintenant une discipline temporelle.',
    s4Title: 'Comment rééquilibrer sans coûts fiscaux excessifs',
    s4intro: 'Le rééquilibrage classique consiste à vendre les gagnants et acheter les perdants. Toutefois, chaque vente en plus-value génère une imposition sur les gains en capital. Il existe des stratégies alternatives pour minimiser l\'impact fiscal :',
    tableHeaders: ['Stratégie', 'Avantage', 'Limite'],
    tableRows: [
      ['Buy-only rebalancing', 'Aucune plus-value réalisée, fiscalement optimal', 'Nécessite de nouveaux apports, fonctionne seulement si la dérive est faible'],
      ['Rééquilibrage complet (achat & vente)', 'Ramène exactement à la composition cible', 'Génère des plus-values imposables sur les positions vendues avec gain'],
      ['Rééquilibrage en retrait', 'Idéal en phase de décumulation', 'Applicable uniquement lors de retraits de capital du portefeuille'],
    ],
    s4conclusion: 'Dans les trois cas, la fonction <strong>Capital Management</strong> de DonkyCapital supporte nativement chaque stratégie : vous pouvez choisir d\'ajouter du capital, de le réduire ou de rééquilibrer sur une composition cible.',
    s5Title: 'Le Capital Management de DonkyCapital',
    s5p1: 'DonkyCapital intègre directement dans le tracker de portefeuille une fonction de <strong>Capital Management</strong> qui calcule automatiquement les ordres nécessaires pour rééquilibrer ou redistribuer le capital — en quelques secondes, avec les prix du marché à jour, sans formules et sans Excel.',
    s5p2: 'La fonctionnalité est disponible pour tous les portefeuilles chargés sur la plateforme, quel que soit le courtier (Fineco, DeGiro, Scalable Capital, Directa et autres).',
    card1Title: 'Increase Capital',
    card1Desc: 'Calcule les ordres d\'achat pour ajouter de nouvelles liquidités tout en maintenant les allocations actuelles.',
    card2Title: 'Reduce Capital',
    card2Desc: 'Calcule les ordres de vente pour retirer du capital tout en conservant les proportions inchangées.',
    card3Title: 'Rebalance',
    card3Desc: 'Calcule les achats et les ventes pour amener le portefeuille à la composition d\'un portefeuille de référence.',
    s6Title: 'Tutoriel pas à pas',
    step1Title: '01. Increase Capital — ajouter des liquidités sans déséquilibrer',
    step1p1: 'Vous avez de nouvelles liquidités à investir et souhaitez les répartir proportionnellement sur les positions existantes ? Sélectionnez <strong>Increase Capital</strong>, saisissez le montant disponible (ex. 10 000 €) et appuyez sur <strong>Calculer</strong>.',
    step1p2: 'Le système traite les prix actuels du marché et renvoie le plan d\'achat optimal : pour chaque instrument en portefeuille, vous verrez la quantité actuelle, la quantité cible, le delta (parts à acheter) et la valeur de l\'ordre. Les liquidités restantes après les achats sont visibles en temps réel.',
    step1note: 'Vous pouvez télécharger les résultats au format CSV pour passer les ordres directement sur la plateforme de votre courtier.',
    step2Title: '02. Reduce Capital — retirer sans déséquilibrer',
    step2p1: 'Vous devez liquider une partie du portefeuille ? Avec <strong>Reduce Capital</strong>, saisissez le montant à retirer et le système calcule quels titres vendre et en quelle quantité, en maintenant les proportions du portefeuille restant.',
    step2p2: 'Le résultat affiche les ordres de vente (SELL) avec les quantités exactes et les valeurs pour chaque instrument, ainsi que les liquidités disponibles après les ventes. Particulièrement utile en phase de décumulation ou en cas de dépenses imprévues.',
    step3Title: '03. Rebalance — retrouver la composition cible',
    step3p1: 'C\'est le mode le plus puissant. Sélectionnez le <strong>portefeuille de référence</strong> — qui peut être le même portefeuille à une date antérieure, ou un <strong>portefeuille entièrement différent</strong> comme modèle cible — et la <strong>date de référence</strong> : DonkyCapital calculera exactement combien de titres acheter, vendre ou conserver (HOLD).',
    step3p2: 'Particulièrement utile si vous gérez plusieurs portefeuilles : vous pouvez aligner un portefeuille satellite sur la composition d\'un portefeuille principal, ou répliquer la structure d\'un portefeuille modèle sur un nouveau compte courtier.',
    step3p3: 'Si le portefeuille est déjà aligné sur la composition cible, le résultat affichera tous les instruments avec l\'action <strong>HOLD</strong>. Vous pouvez également modifier manuellement les <strong>pourcentages cibles</strong> directement dans le tableau des résultats et appuyer sur <strong>Recalculer</strong> pour mettre à jour le plan en temps réel — sans repartir de zéro. Cela vous offre une flexibilité maximale pour tester différents scénarios.',
    faqTitle: 'Questions fréquentes sur le rééquilibrage',
    faq1q: 'À quelle fréquence dois-je rééquilibrer mon portefeuille ?',
    faq1a: 'Pour la plupart des investisseurs, une révision trimestrielle est suffisante. L\'essentiel est de définir un seuil de dérive (ex. ±5 %) au-delà duquel agir. Rééquilibrer trop souvent augmente les frais de transaction et peut générer des plus-values imposables inutiles.',
    faq2q: 'Vaut-il mieux rééquilibrer uniquement par achats ou aussi par ventes ?',
    faq2a: 'Cela dépend de votre phase d\'investissement. En phase d\'accumulation avec de nouvelles liquidités disponibles, le buy-only rebalancing est souvent préférable car il évite l\'imposition des plus-values. Si la dérive est très importante ou en phase de décumulation, le rééquilibrage complet est plus approprié.',
    faq3q: 'Le rééquilibrage de portefeuille génère-t-il des impôts ?',
    faq3a: 'Oui : toute vente d\'instruments financiers avec une plus-value est soumise à l\'impôt sur les gains en capital. C\'est pourquoi le buy-only rebalancing est souvent recommandé en phase d\'accumulation. La fonction « Rebalance » de DonkyCapital affiche clairement les ordres de vente (SELL) pour évaluer l\'impact fiscal avant d\'exécuter.',
    faq4q: 'Le Capital Management fonctionne-t-il avec tous les courtiers ?',
    faq4a: 'Oui. Le Capital Management de DonkyCapital fonctionne avec tous les portefeuilles chargés sur la plateforme, quel que soit le courtier : Fineco, DeGiro, Scalable Capital, Directa et autres. Le système récupère les données actualisées et calcule les ordres sur la base des prix du marché en temps réel.',
    ctaTitle: 'Commencez à gérer votre portefeuille intelligemment',
    ctaDesc: 'Avec DonkyCapital, vous bénéficiez du Capital Management, de widgets analytiques avancés et du suivi unifié de tous vos courtiers — le tout dans un seul tableau de bord. Demandez l\'accès anticipé gratuitement.',
    ctaButton: 'Essayer DonkyCapital gratuitement',
    ctaNote: 'Accès anticipé gratuit · Aucune carte de crédit requise',
  },

  es: {
    badge: 'Guía · Gestión de Cartera',
    h1prefix: 'Cómo Rebalancear tu Cartera de Inversiones: ',
    h1gradient: 'Guía Práctica y Herramienta Automática',
    intro1: 'El <strong>rebalanceo de cartera</strong> es una de las operaciones más importantes para cualquier inversor a largo plazo, pero a menudo se pasa por alto. Los mercados no se mueven todos en la misma dirección: acciones que crecen más rápido que los bonos, un sector que supera a los demás, nuevas aportaciones de capital — todas situaciones que con el tiempo modifican la composición original de la cartera y alteran el perfil de riesgo planificado.',
    intro2: 'En esta guía completa descubrirás qué es el rebalanceo, por qué es esencial, cuándo hacerlo y cómo simplificarlo con la función <strong>Capital Management</strong> integrada en DonkyCapital — sin hojas de cálculo Excel, sin cálculos manuales.',
    tocTitle: 'Índice de contenidos',
    tocItems: [
      'Qué es el rebalanceo de cartera',
      'Por qué la cartera se desequilibra con el tiempo',
      'Cuándo rebalancear: las estrategias más eficaces',
      'Cómo rebalancear sin costes fiscales excesivos',
      'El Capital Management de DonkyCapital',
      'Tutorial paso a paso',
      'Preguntas frecuentes',
    ],
    s1Title: 'Qué es el rebalanceo de cartera',
    s1p1: 'El <strong>rebalancing</strong> (rebalanceo) consiste en devolver los pesos de los activos de una cartera a su composición original o objetivo. Imagina que planificaste una asignación del 60% en renta variable y el 40% en renta fija. Después de un año de subidas bursátiles, la proporción se ha desplazado a 72% acciones y 28% bonos: estás asumiendo más riesgo del planificado.',
    s1p2: 'Rebalancear significa corregir esta deriva: vendes parte de las posiciones sobreponderadas o compras las infraponderadas, hasta volver a la composición planificada. El mismo principio se aplica a una cartera de ETFs, a una asignación sectorial o a una distribución por divisa y área geográfica.',
    s1quote: 'El rebalanceo no es especulación — es disciplina. Es el mecanismo que te permite vender caro y comprar barato de forma sistemática, sin dejarte llevar por la emoción del momento.',
    s2Title: 'Por qué la cartera se desequilibra con el tiempo',
    s2intro: 'La deriva de la cartera es inevitable y depende de varios factores:',
    s2items: [
      '<strong>Crecimiento diferenciado de los activos:</strong> las acciones y los bonos no crecen al mismo ritmo. En mercados alcistas de renta variable, las acciones tienden a superar a los bonos, alterando su peso relativo.',
      '<strong>Dividendos y cupones no reinvertidos:</strong> si los ingresos generados no se redistribuyen proporcionalmente, se acumulan desequilibrios progresivos.',
      '<strong>Nuevas aportaciones de capital:</strong> cada aportación mensual o puntual, si no se distribuye correctamente, altera los pesos de la cartera.',
      '<strong>Reembolsos parciales:</strong> las reducciones de capital que no respetan la composición objetivo modifican las proporciones restantes.',
      '<strong>Efecto divisa:</strong> si tienes ETFs denominados en USD o GBP, las fluctuaciones EUR/divisa modifican el peso real en tu divisa de referencia.',
    ],
    s3Title: 'Cuándo rebalancear: las estrategias más eficaces',
    s3intro: 'No existe una respuesta universal a la pregunta <em>«¿con qué frecuencia debo rebalancear mi cartera?»</em>. Depende de tu estrategia, los costes de transacción y el impacto fiscal. Sin embargo, existen tres enfoques principales:',
    s3card1Title: 'Rebalanceo por calendario',
    s3card1Text: 'Elige una frecuencia fija — trimestral, semestral o anual — y verifica la composición de la cartera independientemente de los movimientos del mercado. Fácil de planificar y ayuda a mantener la disciplina. El inconveniente: podrías intervenir cuando la deriva aún es mínima, incurriendo en costes de transacción innecesarios.',
    s3card2Title: 'Rebalanceo por umbral',
    s3card2Text: 'Actúa solo cuando un activo se desvíe más del 5% (o 10%) de su asignación objetivo. Por ejemplo, si un ETF de renta variable representa el 40% en el plan pero ha alcanzado el 47%, es momento de actuar. Este enfoque reduce los costes en períodos estables, pero requiere una supervisión más frecuente.',
    s3card3Title: 'Enfoque mixto (recomendado)',
    s3card3Text: 'La estrategia más eficiente para la mayoría de los inversores: <strong>revisión trimestral</strong>, pero acción solo si la deriva supera el 5%. Así evitas transacciones innecesarias en períodos estables y mantienes una disciplina temporal.',
    s4Title: 'Cómo rebalancear sin costes fiscales excesivos',
    s4intro: 'El rebalanceo clásico implica vender los ganadores y comprar los perdedores. Sin embargo, cualquier venta con beneficio genera tributación sobre las plusvalías. Existen estrategias alternativas para minimizar el impacto fiscal:',
    tableHeaders: ['Estrategia', 'Ventaja', 'Limitación'],
    tableRows: [
      ['Buy-only rebalancing', 'Sin plusvalías realizadas, óptimo fiscalmente', 'Requiere nueva liquidez, funciona solo si la deriva no es demasiado amplia'],
      ['Rebalanceo completo (compra y venta)', 'Devuelve exactamente a la composición objetivo', 'Genera plusvalías imponibles en posiciones vendidas con ganancia'],
      ['Rebalanceo en reembolso', 'Ideal en la fase de decumulación', 'Solo aplicable si se está retirando capital de la cartera'],
    ],
    s4conclusion: 'En los tres casos, la función <strong>Capital Management</strong> de DonkyCapital soporta nativamente cada estrategia: puedes elegir si añadir capital, reducirlo o rebalancear sobre una composición objetivo.',
    s5Title: 'El Capital Management de DonkyCapital',
    s5p1: 'DonkyCapital integra directamente en el tracker de cartera una función de <strong>Capital Management</strong> que calcula automáticamente las órdenes necesarias para rebalancear o redistribuir el capital — en segundos, con precios de mercado actualizados, sin fórmulas y sin Excel.',
    s5p2: 'La función está disponible para todas las carteras cargadas en la plataforma, independientemente del bróker (Fineco, DeGiro, Scalable Capital, Directa y otros).',
    card1Title: 'Increase Capital',
    card1Desc: 'Calcula las órdenes de compra para añadir nueva liquidez manteniendo las asignaciones actuales.',
    card2Title: 'Reduce Capital',
    card2Desc: 'Calcula las órdenes de venta para retirar capital manteniendo las proporciones inalteradas.',
    card3Title: 'Rebalance',
    card3Desc: 'Calcula compras y ventas para llevar la cartera a la composición de una cartera de referencia.',
    s6Title: 'Tutorial paso a paso',
    step1Title: '01. Increase Capital — añadir liquidez sin desequilibrar',
    step1p1: '¿Tienes nueva liquidez que invertir y quieres distribuirla proporcionalmente entre las posiciones existentes? Selecciona <strong>Increase Capital</strong>, introduce el importe disponible (ej. 10.000€) y pulsa <strong>Calcular</strong>.',
    step1p2: 'El sistema procesa los precios actuales de mercado y devuelve el plan de compra óptimo: para cada instrumento en cartera verás la cantidad actual, la cantidad objetivo, el delta (títulos a comprar) y el valor de la orden. La liquidez restante tras las compras es visible en tiempo real.',
    step1note: 'Puedes descargar los resultados en formato CSV para ejecutar las órdenes directamente en la plataforma de tu bróker.',
    step2Title: '02. Reduce Capital — retirar sin desequilibrar',
    step2p1: '¿Necesitas liquidar parte de la cartera? Con <strong>Reduce Capital</strong> introduce el importe a retirar y el sistema calcula qué valores vender y en qué cantidad, manteniendo las proporciones de la cartera restante.',
    step2p2: 'El resultado muestra las órdenes de venta (SELL) con cantidades exactas y valores para cada instrumento, más la liquidez disponible tras las ventas. Especialmente útil en la fase de decumulación o ante gastos imprevistos.',
    step3Title: '03. Rebalance — volver a la composición objetivo',
    step3p1: 'Es el modo más potente. Selecciona la <strong>cartera de referencia</strong> — que puede ser la misma cartera en una fecha anterior, o una <strong>cartera completamente diferente</strong> como modelo objetivo — y la <strong>fecha de referencia</strong>: DonkyCapital calculará exactamente cuántos valores comprar, vender o mantener (HOLD).',
    step3p2: 'Especialmente útil si gestionas múltiples carteras: puedes alinear una cartera satélite a la composición de una cartera principal, o replicar la estructura de una cartera modelo en una nueva cuenta de bróker.',
    step3p3: 'Si la cartera ya está alineada con la composición objetivo, el resultado mostrará todos los instrumentos con acción <strong>HOLD</strong>. También puedes modificar manualmente los <strong>porcentajes objetivo</strong> directamente en la tabla de resultados y pulsar <strong>Recalcular</strong> para actualizar el plan en tiempo real — sin empezar de cero. Esto te da la máxima flexibilidad para probar distintos escenarios.',
    faqTitle: 'Preguntas frecuentes sobre el rebalanceo',
    faq1q: '¿Con qué frecuencia debo rebalancear mi cartera?',
    faq1a: 'Para la mayoría de los inversores, una revisión trimestral es suficiente. Lo importante es definir un umbral de deriva (ej. ±5%) a partir del cual actuar. Rebalancear con demasiada frecuencia aumenta los costes de transacción y puede generar plusvalías imponibles innecesarias.',
    faq2q: '¿Es mejor rebalancear solo comprando o también vendiendo?',
    faq2a: 'Depende de tu fase de inversión. En acumulación con nueva liquidez disponible, el buy-only rebalancing es a menudo preferible porque evita la tributación sobre las plusvalías. Si la deriva es muy amplia o estás en decumulación, el rebalanceo completo con compras y ventas es más apropiado.',
    faq3q: '¿El rebalanceo de cartera genera impuestos?',
    faq3a: 'Sí: cualquier venta de instrumentos financieros con beneficio está sujeta al impuesto sobre las plusvalías. Por eso el buy-only rebalancing se recomienda a menudo en la fase de acumulación. La función "Rebalance" de DonkyCapital muestra claramente las órdenes de venta (SELL) para evaluar el impacto fiscal antes de ejecutar.',
    faq4q: '¿El Capital Management funciona con todos los brókers?',
    faq4a: 'Sí. El Capital Management de DonkyCapital funciona con todas las carteras cargadas en la plataforma, independientemente del bróker: Fineco, DeGiro, Scalable Capital, Directa y otros. El sistema recupera datos actualizados y calcula las órdenes basándose en los precios actuales de mercado.',
    ctaTitle: 'Empieza a gestionar tu cartera de forma inteligente',
    ctaDesc: 'Con DonkyCapital dispones del Capital Management, widgets analíticos avanzados y el seguimiento unificado de todos tus brókers — todo en un único panel. Solicita el acceso anticipado de forma gratuita.',
    ctaButton: 'Probar DonkyCapital gratis',
    ctaNote: 'Acceso anticipado gratuito · No se requiere tarjeta de crédito',
  },
}
