export interface RoiGuideTranslations {
  badge: string
  h1prefix: string
  h1gradient: string
  intro1: string
  intro2: string
  tocTitle: string
  tocItems: string[]
  s1Title: string
  s1p1: string
  s1bullets: string[]
  s1quote: string
  s2Title: string
  s2p1: string
  s2formulaLabel: string
  s2exampleLabel: string
  s2exampleP: string
  s2proTitle: string
  s2proItems: string[]
  s2conTitle: string
  s2conItems: string[]
  s3Title: string
  s3p1: string
  s3p2: string
  s3formulaLabel: string
  s3formulaNote: string
  s3exampleLabel: string
  s3exampleP: string
  s3exampleItems: string[]
  s3exampleNote: string
  s3proTitle: string
  s3proItems: string[]
  s3conTitle: string
  s3conItems: string[]
  s4Title: string
  s4p1: string
  s4p2: string
  s4formulaLabel: string
  s4formulaNote1: string
  s4formulaNote2: string
  s4exampleLabel: string
  s4exampleP: string
  s4exampleItems: string[]
  s4exampleNote: string
  s4cardTitle: string
  s4cardGt: string
  s4cardLt: string
  s5Title: string
  s5p1: string
  s5col1: string
  s5col2: string
  s5rows: [string, string][]
  s6Title: string
  s6p1: string
  s6bullets: string[]
  s7Title: string
  s7p1: string
  s7port1Title: string
  s7port1Note: string
  s7port2Title: string
  s7port2Note: string
  s7summary: string
  s7labelInvested: string
  s7labelDivested: string
  s7labelValue: string
  s7labelPerformance: string
  s7labelTwrrY: string
  faqTitle: string
  faq1q: string
  faq1a: string
  faq2q: string
  faq2a: string
  faq3q: string
  faq3a: string
  faq4q: string
  faq4a: string
  ctaTitle: string
  ctaDesc: string
  ctaButton: string
  ctaNote: string
}

export const roiGuideContent: Record<string, RoiGuideTranslations> = {
  it: {
    badge: 'Guida · Metriche di Performance',
    h1prefix: 'Rendimento Reale del Portfolio: ',
    h1gradient: 'Differenza tra ROI, TWR e IRR [Con Esempi Pratici]',
    intro1: 'Il tuo broker ti mostra <strong>+83% di performance</strong>. Ma è davvero quello il rendimento del tuo portafoglio? Non sempre. La differenza tra come il broker calcola il guadagno e come dovresti calcolarlo tu può essere enorme — soprattutto se hai fatto versamenti periodici o prelievi nel corso degli anni.',
    intro2: 'In questa guida analizziamo le tre metriche fondamentali per il <strong>calcolo del rendimento del portafoglio</strong>: ROI semplice, TWR (Time-Weighted Return) e IRR/MWRR (Money-Weighted Rate of Return). Con formule, esempi numerici concreti e un case study tratto da dati reali.',
    tocTitle: 'Indice dei contenuti',
    tocItems: [
      'Perché il "Gain %" del broker è fuorviante',
      'ROI Semplice: formula, usi e limiti',
      'TWR / TWRR: la metrica dei benchmark',
      'IRR / MWRR: il rendimento del tuo capitale',
      'Confronto: quale metrica usare in ogni situazione',
      'Come DonkyCapital calcola le metriche in automatico',
      'Case study reale: due portafogli a confronto',
      'Domande frequenti',
    ],
    s1Title: 'Perché il "Gain %" del broker è fuorviante',
    s1p1: 'La percentuale di guadagno mostrata dalla maggior parte dei broker è semplicemente il rapporto tra il profitto attuale e il capitale totale versato. È una misura intuitiva, ma nasconde un problema fondamentale: <strong>non tiene conto di quando hai investito il denaro</strong>.',
    s1bullets: [
      '<strong>Ignora la tempistica dei flussi di cassa</strong>: versamenti aggiuntivi e prelievi distorcono il dato.',
      "<strong>Non è confrontabile con i benchmark</strong>: l'MSCI World o il tuo fondo di riferimento usano TWR, non ROI semplice.",
      "<strong>Varia con l'importo investito</strong>: aggiungere capitale in un momento di ribasso può far sembrare la performance peggiore di quanto sia stata in realtà.",
    ],
    s1quote: 'Il "Gain %" del broker misura quanto è cresciuto il tuo saldo. Non misura la qualità delle tue decisioni di investimento.',
    s2Title: 'ROI Semplice: formula, usi e limiti',
    s2p1: 'Il <strong>Return on Investment (ROI)</strong> semplice — chiamato anche Simple Return o Performance — è la metrica più immediata: quanto vale il portafoglio oggi rispetto a quanto hai investito in totale.',
    s2formulaLabel: 'Formula',
    s2exampleLabel: 'Esempio numerico',
    s2exampleP: 'Hai investito <strong>€6.000</strong> in un ETF. Oggi il portafoglio vale <strong>€10.998</strong>.',
    s2proTitle: 'Quando usarlo',
    s2proItems: [
      'Investimento unico senza versamenti successivi',
      'Confronto rapido tra posizioni singole',
      'Valutazione di un singolo trade',
    ],
    s2conTitle: 'Limiti',
    s2conItems: [
      'Distorto da versamenti e prelievi nel tempo',
      'Non confrontabile con benchmark o altri gestori',
      'Non tiene conto della durata temporale',
    ],
    s3Title: 'TWR / TWRR: la metrica dei benchmark',
    s3p1: "Il <strong>Time-Weighted Rate of Return (TWR o TWRR)</strong> è la metrica standard usata dall'industria finanziaria per misurare la performance di un portafoglio <em>indipendentemente dai flussi di cassa</em>. È obbligatoria per i fondi di investimento proprio perché permette confronti oggettivi: non importa quando il cliente ha aggiunto o ritirato denaro, il TWRR misura solo la bravura nella gestione degli asset.",
    s3p2: "Il principio è semplice: il periodo di investimento viene suddiviso in sotto-periodi ogni volta che c'è un flusso di cassa. Per ogni sotto-periodo si calcola il rendimento, poi si moltiplicano tra loro (compounding).",
    s3formulaLabel: 'Formula',
    s3formulaNote: 'dove R₁...Rₙ sono i rendimenti dei sotto-periodi tra un flusso e l\'altro',
    s3exampleLabel: 'Esempio pratico',
    s3exampleP: "Hai €10.000 investiti. A metà anno aggiungi €5.000. Alla fine dell'anno il portafoglio vale €18.000.",
    s3exampleItems: [
      '→ Sotto-periodo 1 (inizio → versamento): il portafoglio passa da €10.000 a €14.000 → R₁ = +40%',
      '→ Sotto-periodo 2 (versamento → fine anno): da €19.000 a €18.000 → R₂ = −5,3%',
      '→ TWRR = (1,40 × 0,947) − 1 = +32,6%',
    ],
    s3exampleNote: "Il TWRR è +32,6% — riflette solo la performance degli asset, non il fatto che hai aggiunto capitale poco prima del ribasso.",
    s3proTitle: 'Vantaggi',
    s3proItems: [
      'Confrontabile con benchmark (MSCI World, S&P 500)',
      'Non distorto da versamenti/prelievi',
      'Standard internazionale per i fondi (GIPS)',
    ],
    s3conTitle: 'Limiti',
    s3conItems: [
      'Non dice quanto hai guadagnato <em>tu</em> con il tuo capitale',
      "Ignora l'impatto delle tue decisioni sui tempi di investimento",
    ],
    s4Title: 'IRR / MWRR: il rendimento del tuo capitale',
    s4p1: 'Il <strong>Money-Weighted Rate of Return (MWRR)</strong> — noto anche come IRR (Internal Rate of Return) o XIRR in Excel — misura il rendimento effettivo del tuo capitale investito, tenendo conto di <em>quando</em> hai investito ogni euro. A differenza del TWR, l\'IRR assegna più peso ai periodi in cui avevi più capitale investito.',
    s4p2: '<strong>«Qual è il tasso di rendimento annualizzato che rende il valore attuale dei miei flussi di cassa uguale al valore finale del portafoglio?»</strong>',
    s4formulaLabel: 'Definizione (forma intuitiva)',
    s4formulaNote1: 'CFₜ = flusso di cassa al tempo t (negativo se versamento, positivo se prelievo)',
    s4formulaNote2: 'In pratica si usa la funzione XIRR di Excel o viene calcolato automaticamente da strumenti come DonkyCapital',
    s4exampleLabel: 'Esempio pratico — stesso scenario di prima',
    s4exampleP: 'Hai investito €10.000 a inizio anno e €5.000 a metà anno. Fine anno: portafoglio vale €18.000.',
    s4exampleItems: [
      '→ TWRR: +32,6% (visto sopra)',
      '→ MWRR: circa +22%',
      '',
    ],
    s4exampleNote: "Il MWRR è più basso perché hai aggiunto €5.000 <em>dopo</em> che il portafoglio aveva già guadagnato molto (+40%) e subito prima di un ribasso (−5,3%). Il tuo capitale ha subito la perdita su una base più ampia.",
    s4cardTitle: 'TWRR vs MWRR: la differenza chiave',
    s4cardGt: '<strong>TWRR &gt; MWRR</strong>: hai aggiunto capitale in momenti sfavorevoli (a prezzi alti o prima di ribassi). Il mercato ha fatto bene, ma il tuo timing ha ridotto il rendimento reale sul tuo denaro.',
    s4cardLt: '<strong>MWRR &gt; TWRR</strong>: hai investito più capitale nei momenti giusti (a prezzi bassi o prima di rialzi). La tua gestione dei flussi ha amplificato i guadagni rispetto alla pura performance di mercato.',
    s5Title: 'Confronto: quale metrica usare in ogni situazione',
    s5p1: 'Non esiste una metrica "migliore" in assoluto. Ogni misura risponde a una domanda diversa:',
    s5col1: 'Domanda',
    s5col2: 'Metrica da usare',
    s5rows: [
      ['Quanto vale il mio portafoglio rispetto a quanto ho versato?', 'ROI Semplice (Performance %)'],
      ["Sto battendo l'MSCI World o il mio benchmark?", 'TWRR (Time-Weighted Return)'],
      ['Qual è il rendimento annualizzato sul mio capitale?', 'MWRR / IRR (Money-Weighted Return)'],
      ['Ho scelto bene i momenti per investire?', 'Confronto TWRR vs MWRR'],
      ['Devo confrontare due gestori o due fondi?', "TWRR (elimina l'effetto dei flussi)"],
      ['Voglio simulare il rendimento come in Excel con XIRR?', 'MWRR / IRR'],
    ],
    s6Title: 'Come DonkyCapital calcola le metriche in automatico',
    s6p1: "Calcolare manualmente TWRR e MWRR su un portafoglio con decine di transazioni su più broker è complesso e soggetto ad errori. DonkyCapital lo fa automaticamente per tutti i portafogli importati, mostrando <strong>TWRR, TWRR annualizzato e MWRR</strong> affiancati — così puoi leggere il quadro completo in un colpo d'occhio.",
    s6bullets: [
      '<strong>TWRR (Time-Weighted Return Rate)</strong>: rendimento complessivo dalla data di apertura, indipendente dai flussi di cassa.',
      "<strong>TWRR Y (annualizzato)</strong>: il TWRR convertito in tasso annuo — utile per confrontare portafogli aperti in periodi diversi.",
      '<strong>MWRR (Money-Weighted Return Rate)</strong>: il rendimento effettivo sul tuo capitale, tenendo conto di quando hai investito ogni euro.',
    ],
    s7Title: 'Case study reale: due portafogli a confronto',
    s7p1: 'Ecco un esempio concreto tratto dalla dashboard DonkyCapital. Due portafogli con lo stesso capitale investito (€6.000 ciascuno) mostrano metriche molto diverse — e la lettura affiancata di TWRR e MWRR racconta due storie completamente differenti.',
    s7port1Title: 'Portfolio 1 — Forte crescita',
    s7port1Note: 'TWRR (+83%) > MWRR (+56%). Il portafoglio ha performato molto bene, ma l\'investitore ha aggiunto capitale quando le quotazioni erano già alte. Il rendimento effettivo sul denaro investito è inferiore alla performance pura degli asset.',
    s7port2Title: 'Portfolio 2 — Performance negativa',
    s7port2Note: 'TWRR e MWRR quasi coincidono (−0,78% vs −0,68%). Il prelievo di €500 ha avuto un impatto marginale. La piccola differenza indica che i flussi di cassa hanno influito minimamente.',
    s7summary: 'A parità di capitale investito (€6.000), le due metriche raccontano storie diverse. Chi si fermasse al "ROI +83%" sovrastimarebbe il rendimento effettivo. Il MWRR di +56% è la misura più onesta del risultato per quell\'investitore, considerando quando ha allocato il capitale.',
    s7labelInvested: 'Investito',
    s7labelDivested: 'Disinvestito',
    s7labelValue: 'Valore attuale',
    s7labelPerformance: 'Performance (ROI)',
    s7labelTwrrY: 'TWRR annualizzato',
    faqTitle: 'Domande frequenti',
    faq1q: 'TWRR e MWRR danno sempre risultati diversi?',
    faq1a: "No. Se hai investito tutto il capitale in un'unica soluzione senza versamenti o prelievi successivi, TWRR e MWRR coincidono. Le differenze emergono solo in presenza di flussi di cassa multipli nel tempo.",
    faq2q: 'Qual è la differenza tra MWRR e XIRR di Excel?',
    faq2a: "Sono la stessa cosa espressa in modo diverso. L'XIRR di Excel calcola il tasso interno di rendimento tenendo conto delle date esatte di ogni flusso di cassa — è esattamente il MWRR. DonkyCapital usa lo stesso algoritmo automaticamente.",
    faq3q: 'Quale metrica usare per confrontarmi con un ETF o con il MSCI World?',
    faq3a: "Usa sempre il TWRR (o TWRR annualizzato). I benchmark come l'MSCI World sono calcolati con metodo time-weighted. Solo il TWRR garantisce un confronto oggettivo.",
    faq4q: 'Se il mio TWRR è molto più alto del MWRR, è un problema?',
    faq4a: "Non necessariamente. Significa che hai aggiunto capitale in momenti sfavorevoli. È un'informazione preziosa per riflettere sul proprio approccio ai versamenti periodici, ma non indica un errore nella gestione degli asset.",
    ctaTitle: 'Calcola TWRR e MWRR del Tuo Portafoglio',
    ctaDesc: 'Smetti di affidarti al semplice "Gain %" del broker. Con DonkyCapital ottieni ROI, TWRR e MWRR calcolati automaticamente per tutti i tuoi portafogli — su qualsiasi broker.',
    ctaButton: 'Accedi a DonkyCapital Gratis',
    ctaNote: 'Early Access gratuito · Nessuna carta di credito richiesta',
  },

  en: {
    badge: 'Guide · Performance Metrics',
    h1prefix: 'Real Portfolio Return: ',
    h1gradient: 'Difference Between ROI, TWR and IRR [With Practical Examples]',
    intro1: 'Your broker shows you <strong>+83% performance</strong>. But is that really your portfolio\'s return? Not always. The difference between how your broker calculates gain and how you should calculate it can be huge — especially if you have made periodic contributions or withdrawals over the years.',
    intro2: 'In this guide we analyse the three fundamental metrics for <strong>calculating portfolio return</strong>: Simple ROI, TWR (Time-Weighted Return) and IRR/MWRR (Money-Weighted Rate of Return). With formulas, concrete numerical examples and a case study based on real data.',
    tocTitle: 'Table of Contents',
    tocItems: [
      'Why the broker\'s "Gain %" is misleading',
      'Simple ROI: formula, uses and limitations',
      'TWR / TWRR: the benchmark metric',
      'IRR / MWRR: the return on your capital',
      'Comparison: which metric to use in each situation',
      'How DonkyCapital calculates metrics automatically',
      'Real case study: two portfolios compared',
      'Frequently asked questions',
    ],
    s1Title: 'Why the Broker\'s "Gain %" is Misleading',
    s1p1: 'The gain percentage shown by most brokers is simply the ratio between the current profit and the total capital invested. It\'s an intuitive measure, but it hides a fundamental problem: <strong>it does not account for when you invested the money</strong>.',
    s1bullets: [
      '<strong>Ignores the timing of cash flows</strong>: additional contributions and withdrawals distort the figure.',
      '<strong>Not comparable with benchmarks</strong>: the MSCI World or your reference fund uses TWR, not simple ROI.',
      '<strong>Varies with the amount invested</strong>: adding capital during a downturn can make performance look worse than it actually was.',
    ],
    s1quote: 'The broker\'s "Gain %" measures how much your balance grew. It does not measure the quality of your investment decisions.',
    s2Title: 'Simple ROI: Formula, Uses and Limitations',
    s2p1: 'The <strong>Simple Return on Investment (ROI)</strong> — also called Simple Return or Performance — is the most immediate metric: how much the portfolio is worth today compared to how much you have invested in total.',
    s2formulaLabel: 'Formula',
    s2exampleLabel: 'Numerical Example',
    s2exampleP: 'You invested <strong>€6,000</strong> in an ETF. Today the portfolio is worth <strong>€10,998</strong>.',
    s2proTitle: 'When to use it',
    s2proItems: [
      'Single lump-sum investment with no subsequent contributions',
      'Quick comparison between individual positions',
      'Evaluation of a single trade',
    ],
    s2conTitle: 'Limitations',
    s2conItems: [
      'Distorted by contributions and withdrawals over time',
      'Not comparable with benchmarks or other managers',
      'Does not account for the time horizon',
    ],
    s3Title: 'TWR / TWRR: The Benchmark Metric',
    s3p1: 'The <strong>Time-Weighted Rate of Return (TWR or TWRR)</strong> is the standard metric used by the financial industry to measure portfolio performance <em>independently of cash flows</em>. It is mandatory for investment funds precisely because it allows objective comparisons: no matter when the client added or withdrew money, TWRR measures only the quality of asset management.',
    s3p2: 'The principle is simple: the investment period is divided into sub-periods every time there is a cash flow. The return for each sub-period is calculated, then they are multiplied together (compounding).',
    s3formulaLabel: 'Formula',
    s3formulaNote: 'where R₁...Rₙ are the returns of the sub-periods between each cash flow',
    s3exampleLabel: 'Practical Example',
    s3exampleP: 'You have €10,000 invested. Mid-year you add €5,000. At year-end the portfolio is worth €18,000.',
    s3exampleItems: [
      '→ Sub-period 1 (start → contribution): portfolio goes from €10,000 to €14,000 → R₁ = +40%',
      '→ Sub-period 2 (contribution → year-end): from €19,000 to €18,000 → R₂ = −5.3%',
      '→ TWRR = (1.40 × 0.947) − 1 = +32.6%',
    ],
    s3exampleNote: 'The TWRR is +32.6% — it reflects only asset performance, not the fact that you added capital just before the decline.',
    s3proTitle: 'Advantages',
    s3proItems: [
      'Comparable with benchmarks (MSCI World, S&P 500)',
      'Not distorted by contributions/withdrawals',
      'International standard for funds (GIPS)',
    ],
    s3conTitle: 'Limitations',
    s3conItems: [
      'Does not tell you how much <em>you</em> earned on your capital',
      'Ignores the impact of your cash flow timing decisions',
    ],
    s4Title: 'IRR / MWRR: The Return on Your Capital',
    s4p1: 'The <strong>Money-Weighted Rate of Return (MWRR)</strong> — also known as IRR (Internal Rate of Return) or XIRR in Excel — measures the effective return on your invested capital, accounting for <em>when</em> you invested each euro. Unlike TWR, IRR assigns more weight to periods when you had more capital invested.',
    s4p2: '<strong>«What is the annualised rate of return that makes the present value of my cash flows equal to the final portfolio value?»</strong>',
    s4formulaLabel: 'Definition (intuitive form)',
    s4formulaNote1: 'CFₜ = cash flow at time t (negative if contribution, positive if withdrawal)',
    s4formulaNote2: 'In practice, use the XIRR function in Excel or a tool like DonkyCapital which calculates it automatically',
    s4exampleLabel: 'Practical Example — same scenario as above',
    s4exampleP: 'You invested €10,000 at the start of the year and €5,000 mid-year. Year-end: portfolio worth €18,000.',
    s4exampleItems: [
      '→ TWRR: +32.6% (as above)',
      '→ MWRR: approx. +22%',
      '',
    ],
    s4exampleNote: 'The MWRR is lower because you added €5,000 <em>after</em> the portfolio had already gained a lot (+40%) and just before a decline (−5.3%). Your capital bore the loss on a larger base.',
    s4cardTitle: 'TWRR vs MWRR: the key difference',
    s4cardGt: '<strong>TWRR &gt; MWRR</strong>: you added capital at unfavourable times (at high prices or before declines). The market performed well, but your timing reduced the real return on your money.',
    s4cardLt: '<strong>MWRR &gt; TWRR</strong>: you invested more capital at the right moments (at low prices or before rallies). Your cash flow management amplified gains relative to pure market performance.',
    s5Title: 'Comparison: Which Metric to Use in Each Situation',
    s5p1: 'There is no single "best" metric. Each measure answers a different question:',
    s5col1: 'Question',
    s5col2: 'Metric to use',
    s5rows: [
      ['How much is my portfolio worth compared to what I invested?', 'Simple ROI (Performance %)'],
      ['Am I beating the MSCI World or my benchmark?', 'TWRR (Time-Weighted Return)'],
      ['What is the annualised return on my capital?', 'MWRR / IRR (Money-Weighted Return)'],
      ['Did I choose the right moments to invest?', 'TWRR vs MWRR comparison'],
      ['Do I need to compare two managers or two funds?', 'TWRR (eliminates cash flow effect)'],
      ['Do I want to replicate Excel XIRR results?', 'MWRR / IRR'],
    ],
    s6Title: 'How DonkyCapital Calculates Metrics Automatically',
    s6p1: 'Calculating TWRR and MWRR manually on a portfolio with dozens of transactions across multiple brokers is complex and error-prone. DonkyCapital does it automatically for all imported portfolios, showing <strong>TWRR, annualised TWRR and MWRR</strong> side by side — giving you the complete picture at a glance.',
    s6bullets: [
      '<strong>TWRR (Time-Weighted Return Rate)</strong>: cumulative return since the portfolio was opened, independent of cash flows.',
      '<strong>TWRR Y (annualised)</strong>: TWRR converted to an annual rate — useful for comparing portfolios opened at different times.',
      '<strong>MWRR (Money-Weighted Return Rate)</strong>: the effective return on your capital, accounting for when you invested each euro.',
    ],
    s7Title: 'Real Case Study: Two Portfolios Compared',
    s7p1: 'Here is a concrete example from the DonkyCapital dashboard. Two portfolios with the same invested capital (€6,000 each) show very different metrics — and reading TWRR and MWRR side by side tells two completely different stories.',
    s7port1Title: 'Portfolio 1 — Strong growth',
    s7port1Note: 'TWRR (+83%) > MWRR (+56%). The portfolio performed very well, but the investor added capital when prices were already high. The effective return on invested money is lower than the pure asset performance.',
    s7port2Title: 'Portfolio 2 — Negative performance',
    s7port2Note: 'TWRR and MWRR almost coincide (−0.78% vs −0.68%). The €500 withdrawal had a marginal impact. The small difference shows that cash flows had minimal influence.',
    s7summary: 'With the same invested capital (€6,000), the two metrics tell different stories. Stopping at "ROI +83%" would overestimate the effective return. The MWRR of +56% is the most honest measure of that investor\'s result, given when they deployed their capital.',
    s7labelInvested: 'Invested',
    s7labelDivested: 'Divested',
    s7labelValue: 'Current Value',
    s7labelPerformance: 'Performance (ROI)',
    s7labelTwrrY: 'Annualised TWRR',
    faqTitle: 'Frequently Asked Questions',
    faq1q: 'Do TWRR and MWRR always give different results?',
    faq1a: 'No. If you invested all the capital in a single lump sum with no subsequent contributions or withdrawals, TWRR and MWRR are identical. Differences only arise when there are multiple cash flows over time.',
    faq2q: 'What is the difference between MWRR and Excel\'s XIRR?',
    faq2a: 'They are the same thing expressed differently. Excel\'s XIRR calculates the internal rate of return accounting for the exact dates of each cash flow — that is exactly the MWRR. DonkyCapital uses the same algorithm automatically.',
    faq3q: 'Which metric should I use to compare myself with an ETF or the MSCI World?',
    faq3a: 'Always use TWRR (or annualised TWRR). Benchmarks like the MSCI World are calculated using the time-weighted method. Only TWRR guarantees an objective comparison.',
    faq4q: 'If my TWRR is much higher than my MWRR, is that a problem?',
    faq4a: 'Not necessarily. It means you added capital at unfavourable times. It is valuable information to reflect on your approach to periodic contributions, but it does not indicate an error in asset management.',
    ctaTitle: 'Calculate Your Portfolio\'s TWRR and MWRR',
    ctaDesc: 'Stop relying on the simple "Gain %" from your broker. With DonkyCapital you get ROI, TWRR and MWRR calculated automatically for all your portfolios — across any broker.',
    ctaButton: 'Access DonkyCapital Free',
    ctaNote: 'Free Early Access · No credit card required',
  },

  de: {
    badge: 'Leitfaden · Performance-Kennzahlen',
    h1prefix: 'Tatsächliche Portfolio-Rendite: ',
    h1gradient: 'Unterschied zwischen ROI, TWR und IRR [Mit Praxisbeispielen]',
    intro1: 'Dein Broker zeigt dir <strong>+83 % Performance</strong>. Aber ist das wirklich die Rendite deines Portfolios? Nicht immer. Der Unterschied zwischen der Berechnung des Brokers und der korrekten Berechnung kann erheblich sein — besonders wenn du im Laufe der Jahre regelmäßige Einzahlungen oder Entnahmen vorgenommen hast.',
    intro2: 'In diesem Leitfaden analysieren wir die drei grundlegenden Kennzahlen zur <strong>Berechnung der Portfolio-Rendite</strong>: einfacher ROI, TWR (Time-Weighted Return) und IRR/MWRR (Money-Weighted Rate of Return). Mit Formeln, konkreten Zahlenbeispielen und einer Fallstudie mit echten Daten.',
    tocTitle: 'Inhaltsverzeichnis',
    tocItems: [
      'Warum das „Gewinn %" des Brokers irreführend ist',
      'Einfacher ROI: Formel, Verwendung und Grenzen',
      'TWR / TWRR: die Benchmark-Kennzahl',
      'IRR / MWRR: die Rendite deines Kapitals',
      'Vergleich: welche Kennzahl in welcher Situation',
      'Wie DonkyCapital Kennzahlen automatisch berechnet',
      'Echte Fallstudie: zwei Portfolios im Vergleich',
      'Häufig gestellte Fragen',
    ],
    s1Title: 'Warum das „Gewinn %" des Brokers irreführend ist',
    s1p1: 'Der von den meisten Brokern angezeigte Gewinnprozentsatz ist schlicht das Verhältnis zwischen aktuellem Gewinn und gesamtem investiertem Kapital. Es ist eine intuitive Kennzahl, aber sie verbirgt ein grundlegendes Problem: <strong>Sie berücksichtigt nicht, wann du das Geld investiert hast</strong>.',
    s1bullets: [
      '<strong>Ignoriert den Zeitpunkt der Cashflows</strong>: zusätzliche Einzahlungen und Entnahmen verzerren die Zahl.',
      '<strong>Nicht mit Benchmarks vergleichbar</strong>: der MSCI World oder dein Referenzfonds verwendet TWR, nicht den einfachen ROI.',
      '<strong>Variiert mit dem investierten Betrag</strong>: Kapital während eines Kursrückgangs hinzuzufügen kann die Performance schlechter erscheinen lassen als sie tatsächlich war.',
    ],
    s1quote: 'Das „Gewinn %" des Brokers misst, wie viel dein Kontostand gewachsen ist. Es misst nicht die Qualität deiner Anlageentscheidungen.',
    s2Title: 'Einfacher ROI: Formel, Verwendung und Grenzen',
    s2p1: 'Der <strong>einfache Return on Investment (ROI)</strong> — auch Simple Return oder Performance genannt — ist die unmittelbarste Kennzahl: wie viel das Portfolio heute im Vergleich zum gesamten investierten Kapital wert ist.',
    s2formulaLabel: 'Formel',
    s2exampleLabel: 'Zahlenbeispiel',
    s2exampleP: 'Du hast <strong>6.000 €</strong> in einen ETF investiert. Heute ist das Portfolio <strong>10.998 €</strong> wert.',
    s2proTitle: 'Wann verwenden',
    s2proItems: [
      'Einmalinvestition ohne weitere Einzahlungen',
      'Schneller Vergleich einzelner Positionen',
      'Bewertung eines einzelnen Trades',
    ],
    s2conTitle: 'Grenzen',
    s2conItems: [
      'Verzerrt durch Einzahlungen und Entnahmen über die Zeit',
      'Nicht mit Benchmarks oder anderen Managern vergleichbar',
      'Berücksichtigt den Zeithorizont nicht',
    ],
    s3Title: 'TWR / TWRR: Die Benchmark-Kennzahl',
    s3p1: 'Die <strong>Time-Weighted Rate of Return (TWR oder TWRR)</strong> ist die Standardkennzahl der Finanzbranche zur Messung der Portfolio-Performance <em>unabhängig von Cashflows</em>. Sie ist für Investmentfonds genau deshalb obligatorisch, weil sie objektive Vergleiche ermöglicht: Egal wann der Kunde Geld eingezahlt oder abgehoben hat — TWRR misst nur die Qualität des Asset-Managements.',
    s3p2: 'Das Prinzip ist einfach: Der Anlagezeitraum wird bei jedem Cashflow in Teilperioden unterteilt. Für jede Teilperiode wird die Rendite berechnet, dann werden sie multipliziert (Compounding).',
    s3formulaLabel: 'Formel',
    s3formulaNote: 'wobei R₁...Rₙ die Renditen der Teilperioden zwischen den einzelnen Cashflows sind',
    s3exampleLabel: 'Praxisbeispiel',
    s3exampleP: 'Du hast 10.000 € investiert. Mitte des Jahres zahlst du weitere 5.000 € ein. Am Jahresende ist das Portfolio 18.000 € wert.',
    s3exampleItems: [
      '→ Teilperiode 1 (Beginn → Einzahlung): Portfolio steigt von 10.000 € auf 14.000 € → R₁ = +40 %',
      '→ Teilperiode 2 (Einzahlung → Jahresende): von 19.000 € auf 18.000 € → R₂ = −5,3 %',
      '→ TWRR = (1,40 × 0,947) − 1 = +32,6 %',
    ],
    s3exampleNote: 'Der TWRR beträgt +32,6 % — er spiegelt nur die Asset-Performance wider, nicht die Tatsache, dass du Kapital kurz vor dem Rückgang eingezahlt hast.',
    s3proTitle: 'Vorteile',
    s3proItems: [
      'Vergleichbar mit Benchmarks (MSCI World, S&P 500)',
      'Nicht durch Einzahlungen/Entnahmen verzerrt',
      'Internationaler Standard für Fonds (GIPS)',
    ],
    s3conTitle: 'Grenzen',
    s3conItems: [
      'Sagt nicht, wie viel <em>du</em> mit deinem Kapital verdient hast',
      'Ignoriert die Auswirkungen deiner Timing-Entscheidungen',
    ],
    s4Title: 'IRR / MWRR: Die Rendite Deines Kapitals',
    s4p1: 'Die <strong>Money-Weighted Rate of Return (MWRR)</strong> — auch bekannt als IRR (Internal Rate of Return) oder XIRR in Excel — misst die tatsächliche Rendite deines investierten Kapitals unter Berücksichtigung, <em>wann</em> du jeden Euro investiert hast. Im Gegensatz zum TWR gewichtet der IRR Perioden stärker, in denen du mehr Kapital investiert hattest.',
    s4p2: '<strong>«Was ist der annualisierte Renditesatz, der den Barwert meiner Cashflows gleich dem endgültigen Portfoliowert macht?»</strong>',
    s4formulaLabel: 'Definition (intuitive Form)',
    s4formulaNote1: 'CFₜ = Cashflow zum Zeitpunkt t (negativ bei Einzahlung, positiv bei Entnahme)',
    s4formulaNote2: 'In der Praxis verwendet man die XIRR-Funktion in Excel oder ein Tool wie DonkyCapital, das es automatisch berechnet',
    s4exampleLabel: 'Praxisbeispiel — gleiches Szenario wie oben',
    s4exampleP: 'Du hast 10.000 € zu Jahresbeginn und 5.000 € Mitte des Jahres investiert. Jahresende: Portfolio ist 18.000 € wert.',
    s4exampleItems: [
      '→ TWRR: +32,6 % (wie oben)',
      '→ MWRR: ca. +22 %',
      '',
    ],
    s4exampleNote: 'Die MWRR ist niedriger, weil du 5.000 € <em>nachdem</em> das Portfolio bereits viel gewonnen hatte (+40 %) und kurz vor einem Rückgang (−5,3 %) eingezahlt hast. Dein Kapital erlitt den Verlust auf einer größeren Basis.',
    s4cardTitle: 'TWRR vs. MWRR: der entscheidende Unterschied',
    s4cardGt: '<strong>TWRR &gt; MWRR</strong>: Du hast Kapital zu ungünstigen Zeitpunkten eingezahlt (bei hohen Kursen oder vor Rückgängen). Der Markt lief gut, aber dein Timing hat die tatsächliche Rendite auf dein Geld geschmälert.',
    s4cardLt: '<strong>MWRR &gt; TWRR</strong>: Du hast mehr Kapital zu den richtigen Zeitpunkten investiert (bei niedrigen Kursen oder vor Anstiegen). Dein Cashflow-Management hat die Gewinne gegenüber der reinen Marktperformance verstärkt.',
    s5Title: 'Vergleich: Welche Kennzahl in Welcher Situation',
    s5p1: 'Es gibt keine absolut „beste" Kennzahl. Jede Messgröße beantwortet eine andere Frage:',
    s5col1: 'Frage',
    s5col2: 'Zu verwendende Kennzahl',
    s5rows: [
      ['Wie viel ist mein Portfolio im Vergleich zu meinen Einzahlungen wert?', 'Einfacher ROI (Performance %)'],
      ['Schlage ich den MSCI World oder meinen Benchmark?', 'TWRR (Time-Weighted Return)'],
      ['Was ist die annualisierte Rendite meines Kapitals?', 'MWRR / IRR (Money-Weighted Return)'],
      ['Habe ich die richtigen Zeitpunkte zum Investieren gewählt?', 'Vergleich TWRR vs. MWRR'],
      ['Muss ich zwei Manager oder zwei Fonds vergleichen?', 'TWRR (eliminiert Cashflow-Effekte)'],
      ['Möchte ich XIRR-Ergebnisse aus Excel replizieren?', 'MWRR / IRR'],
    ],
    s6Title: 'Wie DonkyCapital Kennzahlen Automatisch Berechnet',
    s6p1: 'TWRR und MWRR manuell für ein Portfolio mit Dutzenden von Transaktionen bei mehreren Brokern zu berechnen ist komplex und fehleranfällig. DonkyCapital erledigt das automatisch für alle importierten Portfolios und zeigt <strong>TWRR, annualisierten TWRR und MWRR</strong> nebeneinander — damit du das vollständige Bild auf einen Blick erhältst.',
    s6bullets: [
      '<strong>TWRR (Time-Weighted Return Rate)</strong>: kumulative Rendite seit der Eröffnung des Portfolios, unabhängig von Cashflows.',
      '<strong>TWRR Y (annualisiert)</strong>: TWRR als Jahresrate — nützlich zum Vergleich von Portfolios, die zu unterschiedlichen Zeiten eröffnet wurden.',
      '<strong>MWRR (Money-Weighted Return Rate)</strong>: die tatsächliche Rendite deines Kapitals unter Berücksichtigung, wann du jeden Euro investiert hast.',
    ],
    s7Title: 'Echte Fallstudie: Zwei Portfolios Im Vergleich',
    s7p1: 'Hier ist ein konkretes Beispiel aus dem DonkyCapital-Dashboard. Zwei Portfolios mit demselben investierten Kapital (je 6.000 €) zeigen sehr unterschiedliche Kennzahlen — und das Nebeneinanderlesen von TWRR und MWRR erzählt zwei völlig verschiedene Geschichten.',
    s7port1Title: 'Portfolio 1 — Starkes Wachstum',
    s7port1Note: 'TWRR (+83 %) > MWRR (+56 %). Das Portfolio hat sehr gut abgeschnitten, aber der Anleger hat Kapital eingezahlt, als die Kurse bereits hoch waren. Die tatsächliche Rendite auf das investierte Geld ist geringer als die reine Asset-Performance.',
    s7port2Title: 'Portfolio 2 — Negative Performance',
    s7port2Note: 'TWRR und MWRR stimmen fast überein (−0,78 % vs. −0,68 %). Die Entnahme von 500 € hatte einen marginalen Einfluss. Der kleine Unterschied zeigt, dass Cashflows nur minimal gewirkt haben.',
    s7summary: 'Bei gleichem investiertem Kapital (6.000 €) erzählen die beiden Kennzahlen unterschiedliche Geschichten. Wer beim „ROI +83 %" stehen bleibt, würde die tatsächliche Rendite überschätzen. Die MWRR von +56 % ist das ehrlichere Maß für das Ergebnis dieses Anlegers, angesichts des Zeitpunkts seiner Kapitalanlage.',
    s7labelInvested: 'Investiert',
    s7labelDivested: 'Desinvestiert',
    s7labelValue: 'Aktueller Wert',
    s7labelPerformance: 'Performance (ROI)',
    s7labelTwrrY: 'TWRR annualisiert',
    faqTitle: 'Häufig Gestellte Fragen',
    faq1q: 'Ergeben TWRR und MWRR immer unterschiedliche Ergebnisse?',
    faq1a: 'Nein. Wenn du das gesamte Kapital in einer einzigen Einmalanlage ohne nachfolgende Einzahlungen oder Entnahmen investiert hast, sind TWRR und MWRR identisch. Unterschiede entstehen nur bei mehreren Cashflows über die Zeit.',
    faq2q: 'Was ist der Unterschied zwischen MWRR und XIRR in Excel?',
    faq2a: 'Es ist dasselbe, nur anders ausgedrückt. Die XIRR-Funktion von Excel berechnet den internen Zinsfuß unter Berücksichtigung der genauen Daten jedes Cashflows — das ist genau die MWRR. DonkyCapital verwendet denselben Algorithmus automatisch.',
    faq3q: 'Welche Kennzahl sollte ich verwenden, um mich mit einem ETF oder dem MSCI World zu vergleichen?',
    faq3a: 'Verwende immer den TWRR (oder annualisierten TWRR). Benchmarks wie der MSCI World werden nach der zeitgewichteten Methode berechnet. Nur der TWRR garantiert einen objektiven Vergleich.',
    faq4q: 'Wenn mein TWRR viel höher ist als mein MWRR, ist das ein Problem?',
    faq4a: 'Nicht unbedingt. Es bedeutet, dass du Kapital zu ungünstigen Zeitpunkten eingezahlt hast. Es sind wertvolle Informationen, um über den eigenen Ansatz bei regelmäßigen Einzahlungen nachzudenken, zeigt aber keinen Fehler im Asset-Management.',
    ctaTitle: 'Berechne TWRR und MWRR Deines Portfolios',
    ctaDesc: 'Verlasse dich nicht mehr auf das einfache „Gewinn %" deines Brokers. Mit DonkyCapital erhältst du ROI, TWRR und MWRR automatisch berechnet für alle deine Portfolios — bei jedem Broker.',
    ctaButton: 'Zugang zu DonkyCapital kostenlos',
    ctaNote: 'Kostenloser Early Access · Keine Kreditkarte erforderlich',
  },

  fr: {
    badge: 'Guide · Métriques de Performance',
    h1prefix: 'Rendement Réel du Portefeuille : ',
    h1gradient: 'Différence entre ROI, TWR et IRR [Avec Exemples Pratiques]',
    intro1: 'Votre courtier vous affiche <strong>+83 % de performance</strong>. Mais est-ce vraiment le rendement de votre portefeuille ? Pas toujours. La différence entre la façon dont votre courtier calcule le gain et la façon dont vous devriez le calculer peut être énorme — surtout si vous avez effectué des versements périodiques ou des retraits au fil des années.',
    intro2: 'Dans ce guide, nous analysons les trois métriques fondamentales pour le <strong>calcul du rendement du portefeuille</strong> : ROI simple, TWR (Time-Weighted Return) et IRR/MWRR (Money-Weighted Rate of Return). Avec des formules, des exemples numériques concrets et une étude de cas basée sur des données réelles.',
    tocTitle: 'Table des matières',
    tocItems: [
      'Pourquoi le « Gain % » du courtier est trompeur',
      'ROI Simple : formule, utilisations et limites',
      'TWR / TWRR : la métrique des benchmarks',
      'IRR / MWRR : le rendement de votre capital',
      'Comparaison : quelle métrique utiliser dans chaque situation',
      'Comment DonkyCapital calcule les métriques automatiquement',
      'Étude de cas réelle : deux portefeuilles comparés',
      'Questions fréquentes',
    ],
    s1Title: 'Pourquoi le « Gain % » du Courtier est Trompeur',
    s1p1: 'Le pourcentage de gain affiché par la plupart des courtiers est simplement le rapport entre le profit actuel et le capital total investi. C\'est une mesure intuitive, mais elle cache un problème fondamental : <strong>elle ne tient pas compte du moment où vous avez investi l\'argent</strong>.',
    s1bullets: [
      '<strong>Ignore le calendrier des flux de trésorerie</strong> : les versements supplémentaires et les retraits faussent le chiffre.',
      '<strong>Non comparable aux benchmarks</strong> : le MSCI World ou votre fonds de référence utilise le TWR, pas le ROI simple.',
      '<strong>Varie selon le montant investi</strong> : ajouter du capital lors d\'une baisse peut faire paraître la performance pire qu\'elle ne l\'était réellement.',
    ],
    s1quote: 'Le « Gain % » du courtier mesure la croissance de votre solde. Il ne mesure pas la qualité de vos décisions d\'investissement.',
    s2Title: 'ROI Simple : Formule, Utilisations et Limites',
    s2p1: 'Le <strong>Return on Investment (ROI) simple</strong> — appelé aussi Simple Return ou Performance — est la métrique la plus immédiate : combien vaut le portefeuille aujourd\'hui par rapport à ce que vous avez investi au total.',
    s2formulaLabel: 'Formule',
    s2exampleLabel: 'Exemple numérique',
    s2exampleP: 'Vous avez investi <strong>6 000 €</strong> dans un ETF. Aujourd\'hui le portefeuille vaut <strong>10 998 €</strong>.',
    s2proTitle: 'Quand l\'utiliser',
    s2proItems: [
      'Investissement unique sans versements ultérieurs',
      'Comparaison rapide entre positions individuelles',
      'Évaluation d\'un trade unique',
    ],
    s2conTitle: 'Limites',
    s2conItems: [
      'Faussé par les versements et retraits au fil du temps',
      'Non comparable avec les benchmarks ou d\'autres gérants',
      'Ne tient pas compte de la durée temporelle',
    ],
    s3Title: 'TWR / TWRR : La Métrique des Benchmarks',
    s3p1: 'Le <strong>Time-Weighted Rate of Return (TWR ou TWRR)</strong> est la métrique standard utilisée par l\'industrie financière pour mesurer la performance d\'un portefeuille <em>indépendamment des flux de trésorerie</em>. Elle est obligatoire pour les fonds d\'investissement précisément parce qu\'elle permet des comparaisons objectives : peu importe quand le client a ajouté ou retiré de l\'argent, le TWRR ne mesure que la qualité de la gestion des actifs.',
    s3p2: 'Le principe est simple : la période d\'investissement est divisée en sous-périodes à chaque flux de trésorerie. Le rendement de chaque sous-période est calculé, puis ils sont multipliés entre eux (capitalisation).',
    s3formulaLabel: 'Formule',
    s3formulaNote: 'où R₁...Rₙ sont les rendements des sous-périodes entre chaque flux de trésorerie',
    s3exampleLabel: 'Exemple pratique',
    s3exampleP: 'Vous avez 10 000 € investis. En milieu d\'année vous ajoutez 5 000 €. En fin d\'année le portefeuille vaut 18 000 €.',
    s3exampleItems: [
      '→ Sous-période 1 (début → versement) : le portefeuille passe de 10 000 € à 14 000 € → R₁ = +40 %',
      '→ Sous-période 2 (versement → fin d\'année) : de 19 000 € à 18 000 € → R₂ = −5,3 %',
      '→ TWRR = (1,40 × 0,947) − 1 = +32,6 %',
    ],
    s3exampleNote: 'Le TWRR est de +32,6 % — il ne reflète que la performance des actifs, pas le fait que vous avez ajouté du capital juste avant la baisse.',
    s3proTitle: 'Avantages',
    s3proItems: [
      'Comparable aux benchmarks (MSCI World, S&P 500)',
      'Non faussé par les versements/retraits',
      'Norme internationale pour les fonds (GIPS)',
    ],
    s3conTitle: 'Limites',
    s3conItems: [
      'Ne dit pas combien <em>vous</em> avez gagné sur votre capital',
      'Ignore l\'impact de vos décisions de timing sur les flux',
    ],
    s4Title: 'IRR / MWRR : Le Rendement de Votre Capital',
    s4p1: 'Le <strong>Money-Weighted Rate of Return (MWRR)</strong> — également connu sous le nom d\'IRR (Internal Rate of Return) ou XIRR dans Excel — mesure le rendement effectif de votre capital investi, en tenant compte de <em>quand</em> vous avez investi chaque euro. Contrairement au TWR, l\'IRR accorde plus de poids aux périodes où vous aviez plus de capital investi.',
    s4p2: '<strong>«Quel est le taux de rendement annualisé qui rend la valeur actuelle de mes flux de trésorerie égale à la valeur finale du portefeuille ?»</strong>',
    s4formulaLabel: 'Définition (forme intuitive)',
    s4formulaNote1: 'CFₜ = flux de trésorerie au temps t (négatif si versement, positif si retrait)',
    s4formulaNote2: 'En pratique, utilisez la fonction XIRR d\'Excel ou un outil comme DonkyCapital qui le calcule automatiquement',
    s4exampleLabel: 'Exemple pratique — même scénario que ci-dessus',
    s4exampleP: 'Vous avez investi 10 000 € en début d\'année et 5 000 € en milieu d\'année. Fin d\'année : portefeuille vaut 18 000 €.',
    s4exampleItems: [
      '→ TWRR : +32,6 % (comme ci-dessus)',
      '→ MWRR : environ +22 %',
      '',
    ],
    s4exampleNote: 'La MWRR est plus faible parce que vous avez ajouté 5 000 € <em>après</em> que le portefeuille avait déjà beaucoup gagné (+40 %) et juste avant une baisse (−5,3 %). Votre capital a subi la perte sur une base plus large.',
    s4cardTitle: 'TWRR vs MWRR : la différence clé',
    s4cardGt: '<strong>TWRR &gt; MWRR</strong> : vous avez ajouté du capital à des moments défavorables (à prix élevés ou avant des baisses). Le marché a bien performé, mais votre timing a réduit le rendement réel sur votre argent.',
    s4cardLt: '<strong>MWRR &gt; TWRR</strong> : vous avez investi plus de capital aux bons moments (à prix bas ou avant des hausses). Votre gestion des flux a amplifié les gains par rapport à la pure performance du marché.',
    s5Title: 'Comparaison : Quelle Métrique Utiliser Dans Chaque Situation',
    s5p1: 'Il n\'existe pas de métrique « meilleure » en absolu. Chaque mesure répond à une question différente :',
    s5col1: 'Question',
    s5col2: 'Métrique à utiliser',
    s5rows: [
      ['Combien vaut mon portefeuille par rapport à ce que j\'ai versé ?', 'ROI Simple (Performance %)'],
      ['Est-ce que je bats le MSCI World ou mon benchmark ?', 'TWRR (Time-Weighted Return)'],
      ['Quel est le rendement annualisé de mon capital ?', 'MWRR / IRR (Money-Weighted Return)'],
      ['Ai-je bien choisi les moments pour investir ?', 'Comparaison TWRR vs MWRR'],
      ['Dois-je comparer deux gérants ou deux fonds ?', 'TWRR (élimine l\'effet des flux)'],
      ['Veux-je reproduire les résultats XIRR d\'Excel ?', 'MWRR / IRR'],
    ],
    s6Title: 'Comment DonkyCapital Calcule les Métriques Automatiquement',
    s6p1: 'Calculer manuellement TWRR et MWRR sur un portefeuille avec des dizaines de transactions sur plusieurs courtiers est complexe et source d\'erreurs. DonkyCapital le fait automatiquement pour tous les portefeuilles importés, affichant <strong>TWRR, TWRR annualisé et MWRR</strong> côte à côte — pour que vous puissiez voir l\'image complète d\'un coup d\'œil.',
    s6bullets: [
      '<strong>TWRR (Time-Weighted Return Rate)</strong> : rendement cumulé depuis l\'ouverture du portefeuille, indépendant des flux de trésorerie.',
      '<strong>TWRR Y (annualisé)</strong> : le TWRR converti en taux annuel — utile pour comparer des portefeuilles ouverts à des moments différents.',
      '<strong>MWRR (Money-Weighted Return Rate)</strong> : le rendement effectif sur votre capital, en tenant compte du moment où vous avez investi chaque euro.',
    ],
    s7Title: 'Étude de Cas Réelle : Deux Portefeuilles Comparés',
    s7p1: 'Voici un exemple concret tiré du tableau de bord DonkyCapital. Deux portefeuilles avec le même capital investi (6 000 € chacun) affichent des métriques très différentes — et la lecture côte à côte de TWRR et MWRR raconte deux histoires complètement différentes.',
    s7port1Title: 'Portefeuille 1 — Forte croissance',
    s7port1Note: 'TWRR (+83 %) > MWRR (+56 %). Le portefeuille a très bien performé, mais l\'investisseur a ajouté du capital quand les cours étaient déjà élevés. Le rendement effectif sur l\'argent investi est inférieur à la pure performance des actifs.',
    s7port2Title: 'Portefeuille 2 — Performance négative',
    s7port2Note: 'TWRR et MWRR coïncident presque (−0,78 % vs −0,68 %). Le retrait de 500 € a eu un impact marginal. La petite différence montre que les flux de trésorerie ont eu une influence minimale.',
    s7summary: 'À capital investi égal (6 000 €), les deux métriques racontent des histoires différentes. S\'arrêter au « ROI +83 % » surestimerait le rendement effectif. La MWRR de +56 % est la mesure la plus honnête du résultat de cet investisseur, compte tenu du moment où il a déployé son capital.',
    s7labelInvested: 'Investi',
    s7labelDivested: 'Désinvesti',
    s7labelValue: 'Valeur actuelle',
    s7labelPerformance: 'Performance (ROI)',
    s7labelTwrrY: 'TWRR annualisé',
    faqTitle: 'Questions Fréquentes',
    faq1q: 'TWRR et MWRR donnent-ils toujours des résultats différents ?',
    faq1a: 'Non. Si vous avez investi tout le capital en une seule fois sans versements ni retraits ultérieurs, TWRR et MWRR sont identiques. Les différences n\'apparaissent qu\'en présence de flux de trésorerie multiples dans le temps.',
    faq2q: 'Quelle est la différence entre MWRR et XIRR d\'Excel ?',
    faq2a: 'C\'est la même chose exprimée différemment. La fonction XIRR d\'Excel calcule le taux de rendement interne en tenant compte des dates exactes de chaque flux de trésorerie — c\'est exactement le MWRR. DonkyCapital utilise le même algorithme automatiquement.',
    faq3q: 'Quelle métrique utiliser pour me comparer à un ETF ou au MSCI World ?',
    faq3a: 'Utilisez toujours le TWRR (ou TWRR annualisé). Les benchmarks comme le MSCI World sont calculés selon la méthode time-weighted. Seul le TWRR garantit une comparaison objective.',
    faq4q: 'Si mon TWRR est bien supérieur à mon MWRR, est-ce un problème ?',
    faq4a: 'Pas nécessairement. Cela signifie que vous avez ajouté du capital à des moments défavorables. C\'est une information précieuse pour réfléchir à votre approche des versements périodiques, mais ne signifie pas une erreur dans la gestion des actifs.',
    ctaTitle: 'Calculez le TWRR et le MWRR de Votre Portefeuille',
    ctaDesc: 'Arrêtez de vous fier au simple « Gain % » de votre courtier. Avec DonkyCapital, obtenez ROI, TWRR et MWRR calculés automatiquement pour tous vos portefeuilles — quel que soit le courtier.',
    ctaButton: 'Accéder à DonkyCapital Gratuitement',
    ctaNote: 'Early Access gratuit · Aucune carte de crédit requise',
  },

  es: {
    badge: 'Guía · Métricas de Rendimiento',
    h1prefix: 'Rendimiento Real del Portfolio: ',
    h1gradient: 'Diferencia entre ROI, TWR e IRR [Con Ejemplos Prácticos]',
    intro1: 'Tu bróker te muestra <strong>+83 % de performance</strong>. Pero ¿es realmente ese el rendimiento de tu cartera? No siempre. La diferencia entre cómo calcula la ganancia tu bróker y cómo deberías calcularla tú puede ser enorme — especialmente si has realizado aportaciones periódicas o retiradas a lo largo de los años.',
    intro2: 'En esta guía analizamos las tres métricas fundamentales para el <strong>cálculo del rendimiento de la cartera</strong>: ROI simple, TWR (Time-Weighted Return) e IRR/MWRR (Money-Weighted Rate of Return). Con fórmulas, ejemplos numéricos concretos y un caso de estudio basado en datos reales.',
    tocTitle: 'Tabla de contenidos',
    tocItems: [
      'Por qué el "Gain %" del bróker es engañoso',
      'ROI Simple: fórmula, usos y limitaciones',
      'TWR / TWRR: la métrica de los benchmarks',
      'IRR / MWRR: el rendimiento de tu capital',
      'Comparativa: qué métrica usar en cada situación',
      'Cómo DonkyCapital calcula las métricas automáticamente',
      'Caso de estudio real: dos carteras comparadas',
      'Preguntas frecuentes',
    ],
    s1Title: 'Por Qué el "Gain %" del Bróker es Engañoso',
    s1p1: 'El porcentaje de ganancia que muestra la mayoría de los brókers es simplemente la relación entre el beneficio actual y el capital total invertido. Es una medida intuitiva, pero oculta un problema fundamental: <strong>no tiene en cuenta cuándo invertiste el dinero</strong>.',
    s1bullets: [
      '<strong>Ignora el calendario de los flujos de caja</strong>: las aportaciones adicionales y las retiradas distorsionan la cifra.',
      '<strong>No es comparable con los benchmarks</strong>: el MSCI World o tu fondo de referencia usa TWR, no ROI simple.',
      '<strong>Varía con el importe invertido</strong>: añadir capital durante una caída puede hacer que la rentabilidad parezca peor de lo que realmente fue.',
    ],
    s1quote: 'El "Gain %" del bróker mide cuánto creció tu saldo. No mide la calidad de tus decisiones de inversión.',
    s2Title: 'ROI Simple: Fórmula, Usos y Limitaciones',
    s2p1: 'El <strong>Return on Investment (ROI) simple</strong> — también llamado Simple Return o Performance — es la métrica más inmediata: cuánto vale la cartera hoy en comparación con cuánto has invertido en total.',
    s2formulaLabel: 'Fórmula',
    s2exampleLabel: 'Ejemplo numérico',
    s2exampleP: 'Has invertido <strong>6.000 €</strong> en un ETF. Hoy la cartera vale <strong>10.998 €</strong>.',
    s2proTitle: 'Cuándo usarlo',
    s2proItems: [
      'Inversión única sin aportaciones posteriores',
      'Comparación rápida entre posiciones individuales',
      'Evaluación de una operación concreta',
    ],
    s2conTitle: 'Limitaciones',
    s2conItems: [
      'Distorsionado por aportaciones y retiradas a lo largo del tiempo',
      'No comparable con benchmarks ni con otros gestores',
      'No tiene en cuenta el horizonte temporal',
    ],
    s3Title: 'TWR / TWRR: La Métrica de los Benchmarks',
    s3p1: 'El <strong>Time-Weighted Rate of Return (TWR o TWRR)</strong> es la métrica estándar utilizada por la industria financiera para medir el rendimiento de una cartera <em>independientemente de los flujos de caja</em>. Es obligatoria para los fondos de inversión precisamente porque permite comparaciones objetivas: no importa cuándo el cliente añadió o retiró dinero, el TWRR mide únicamente la calidad en la gestión de activos.',
    s3p2: 'El principio es sencillo: el período de inversión se divide en subperíodos cada vez que hay un flujo de caja. Se calcula el rendimiento de cada subperíodo y luego se multiplican entre sí (capitalización compuesta).',
    s3formulaLabel: 'Fórmula',
    s3formulaNote: 'donde R₁...Rₙ son los rendimientos de los subperíodos entre cada flujo de caja',
    s3exampleLabel: 'Ejemplo práctico',
    s3exampleP: 'Tienes 10.000 € invertidos. A mitad de año añades 5.000 €. A final de año la cartera vale 18.000 €.',
    s3exampleItems: [
      '→ Subperíodo 1 (inicio → aportación): la cartera pasa de 10.000 € a 14.000 € → R₁ = +40 %',
      '→ Subperíodo 2 (aportación → fin de año): de 19.000 € a 18.000 € → R₂ = −5,3 %',
      '→ TWRR = (1,40 × 0,947) − 1 = +32,6 %',
    ],
    s3exampleNote: 'El TWRR es +32,6 % — refleja únicamente el rendimiento de los activos, no el hecho de que añadiste capital justo antes de la caída.',
    s3proTitle: 'Ventajas',
    s3proItems: [
      'Comparable con benchmarks (MSCI World, S&P 500)',
      'No distorsionado por aportaciones/retiradas',
      'Estándar internacional para fondos (GIPS)',
    ],
    s3conTitle: 'Limitaciones',
    s3conItems: [
      'No dice cuánto has ganado <em>tú</em> con tu capital',
      'Ignora el impacto de tus decisiones de timing en los flujos',
    ],
    s4Title: 'IRR / MWRR: El Rendimiento de Tu Capital',
    s4p1: 'El <strong>Money-Weighted Rate of Return (MWRR)</strong> — también conocido como IRR (Internal Rate of Return) o XIRR en Excel — mide el rendimiento efectivo de tu capital invertido, teniendo en cuenta <em>cuándo</em> invertiste cada euro. A diferencia del TWR, el IRR asigna mayor peso a los períodos en que tenías más capital invertido.',
    s4p2: '<strong>«¿Cuál es la tasa de rendimiento anualizada que hace que el valor actual de mis flujos de caja sea igual al valor final de la cartera?»</strong>',
    s4formulaLabel: 'Definición (forma intuitiva)',
    s4formulaNote1: 'CFₜ = flujo de caja en el tiempo t (negativo si aportación, positivo si retirada)',
    s4formulaNote2: 'En la práctica se usa la función XIRR de Excel o una herramienta como DonkyCapital que lo calcula automáticamente',
    s4exampleLabel: 'Ejemplo práctico — mismo escenario que antes',
    s4exampleP: 'Invertiste 10.000 € a principio de año y 5.000 € a mitad de año. Fin de año: la cartera vale 18.000 €.',
    s4exampleItems: [
      '→ TWRR: +32,6 % (como arriba)',
      '→ MWRR: aproximadamente +22 %',
      '',
    ],
    s4exampleNote: 'La MWRR es menor porque añadiste 5.000 € <em>después</em> de que la cartera ya hubiera ganado mucho (+40 %) y justo antes de una caída (−5,3 %). Tu capital sufrió la pérdida sobre una base mayor.',
    s4cardTitle: 'TWRR vs MWRR: la diferencia clave',
    s4cardGt: '<strong>TWRR &gt; MWRR</strong>: añadiste capital en momentos desfavorables (a precios altos o antes de caídas). El mercado lo hizo bien, pero tu timing redujo el rendimiento real sobre tu dinero.',
    s4cardLt: '<strong>MWRR &gt; TWRR</strong>: invertiste más capital en los momentos adecuados (a precios bajos o antes de subidas). Tu gestión de los flujos amplificó las ganancias respecto a la pura rentabilidad del mercado.',
    s5Title: 'Comparativa: Qué Métrica Usar en Cada Situación',
    s5p1: 'No existe una métrica "mejor" en términos absolutos. Cada medida responde a una pregunta diferente:',
    s5col1: 'Pregunta',
    s5col2: 'Métrica a usar',
    s5rows: [
      ['¿Cuánto vale mi cartera respecto a lo que he invertido?', 'ROI Simple (Performance %)'],
      ['¿Estoy batiendo al MSCI World o a mi benchmark?', 'TWRR (Time-Weighted Return)'],
      ['¿Cuál es el rendimiento anualizado de mi capital?', 'MWRR / IRR (Money-Weighted Return)'],
      ['¿He elegido bien los momentos para invertir?', 'Comparación TWRR vs MWRR'],
      ['¿Necesito comparar dos gestores o dos fondos?', 'TWRR (elimina el efecto de los flujos)'],
      ['¿Quiero replicar los resultados de XIRR de Excel?', 'MWRR / IRR'],
    ],
    s6Title: 'Cómo DonkyCapital Calcula las Métricas Automáticamente',
    s6p1: 'Calcular manualmente TWRR y MWRR en una cartera con decenas de transacciones en varios brókers es complejo y propenso a errores. DonkyCapital lo hace automáticamente para todas las carteras importadas, mostrando <strong>TWRR, TWRR anualizado y MWRR</strong> en paralelo — para que puedas ver el panorama completo de un vistazo.',
    s6bullets: [
      '<strong>TWRR (Time-Weighted Return Rate)</strong>: rendimiento acumulado desde la apertura de la cartera, independiente de los flujos de caja.',
      '<strong>TWRR Y (anualizado)</strong>: el TWRR convertido a tasa anual — útil para comparar carteras abiertas en momentos distintos.',
      '<strong>MWRR (Money-Weighted Return Rate)</strong>: el rendimiento efectivo sobre tu capital, teniendo en cuenta cuándo invertiste cada euro.',
    ],
    s7Title: 'Caso de Estudio Real: Dos Carteras Comparadas',
    s7p1: 'Aquí tienes un ejemplo concreto extraído del panel de DonkyCapital. Dos carteras con el mismo capital invertido (6.000 € cada una) muestran métricas muy diferentes — y la lectura paralela de TWRR y MWRR cuenta dos historias completamente distintas.',
    s7port1Title: 'Cartera 1 — Fuerte crecimiento',
    s7port1Note: 'TWRR (+83 %) > MWRR (+56 %). La cartera ha rendido muy bien, pero el inversor añadió capital cuando los precios ya eran altos. El rendimiento efectivo sobre el dinero invertido es menor que la pura rentabilidad de los activos.',
    s7port2Title: 'Cartera 2 — Rendimiento negativo',
    s7port2Note: 'TWRR y MWRR casi coinciden (−0,78 % vs −0,68 %). La retirada de 500 € tuvo un impacto marginal. La pequeña diferencia muestra que los flujos de caja influyeron mínimamente.',
    s7summary: 'Con el mismo capital invertido (6.000 €), las dos métricas cuentan historias diferentes. Quedarse en el "ROI +83 %" sobreestimaría el rendimiento efectivo. La MWRR del +56 % es la medida más honesta del resultado de ese inversor, dado el momento en que desplegó su capital.',
    s7labelInvested: 'Invertido',
    s7labelDivested: 'Desinvertido',
    s7labelValue: 'Valor actual',
    s7labelPerformance: 'Performance (ROI)',
    s7labelTwrrY: 'TWRR anualizado',
    faqTitle: 'Preguntas Frecuentes',
    faq1q: '¿TWRR y MWRR siempre dan resultados diferentes?',
    faq1a: 'No. Si invertiste todo el capital en una única aportación sin contribuciones ni retiradas posteriores, TWRR y MWRR son idénticos. Las diferencias solo aparecen cuando hay múltiples flujos de caja a lo largo del tiempo.',
    faq2q: '¿Cuál es la diferencia entre MWRR y XIRR de Excel?',
    faq2a: 'Son lo mismo expresado de manera diferente. La función XIRR de Excel calcula la tasa interna de rendimiento teniendo en cuenta las fechas exactas de cada flujo de caja — eso es exactamente el MWRR. DonkyCapital utiliza el mismo algoritmo automáticamente.',
    faq3q: '¿Qué métrica usar para compararme con un ETF o el MSCI World?',
    faq3a: 'Usa siempre el TWRR (o TWRR anualizado). Los benchmarks como el MSCI World se calculan con el método time-weighted. Solo el TWRR garantiza una comparación objetiva.',
    faq4q: 'Si mi TWRR es mucho mayor que mi MWRR, ¿es un problema?',
    faq4a: 'No necesariamente. Significa que añadiste capital en momentos desfavorables. Es información valiosa para reflexionar sobre tu enfoque de las aportaciones periódicas, pero no indica un error en la gestión de activos.',
    ctaTitle: 'Calcula el TWRR y el MWRR de Tu Cartera',
    ctaDesc: 'Deja de confiar en el simple "Gain %" de tu bróker. Con DonkyCapital obtienes ROI, TWRR y MWRR calculados automáticamente para todas tus carteras — en cualquier bróker.',
    ctaButton: 'Acceder a DonkyCapital Gratis',
    ctaNote: 'Early Access gratuito · Sin tarjeta de crédito requerida',
  },
}
